"""
Rice Aman risk evaluator.
Auto-generated by build_crop_profiles_pipeline.py — do not edit manually.
Uses DayForecast dicts as stored in ArangoDB weather_forecasts collection.
"""

from __future__ import annotations

from dataclasses import dataclass

from app.crops.rice_aman.profile import RiceAmanThresholds

_TIER_LABELS = {0: "Normal", 1: "Advisory", 2: "Warning", 3: "Severe", 4: "Emergency"}


@dataclass
class DailyForecastPoint:
    date: str
    temp_min: float
    temp_max: float
    humidity_max: float
    humidity_min: float
    rain_mm: float
    wind_kmh: float
    source: str


def to_point_from_dict(day: dict, source: str) -> DailyForecastPoint:
    """Convert a raw ArangoDB DayForecast dict to DailyForecastPoint."""
    # `humidity` is the daily maximum. Older documents and the BMD source
    # carry only that one value; fall back to it so a missing daily minimum
    # cannot silently read as 0% and fire a dryness trigger.
    return DailyForecastPoint(
        date=day["date"],
        temp_min=day["temperature"]["min"],
        temp_max=day["temperature"]["max"],
        humidity_max=day["humidity"],
        humidity_min=day.get("humidity_min") or day["humidity"],
        rain_mm=day["precipitation"]["value"],
        wind_kmh=day["wind"]["speed"],
        source=source,
    )


def evaluate_rice_aman_day(day: DailyForecastPoint, t: RiceAmanThresholds) -> list[str]:
    """Return threshold breaches for one forecast day."""
    triggers: list[str] = []

    if day.temp_max > t.temp_max:
        triggers.append(
            f"Max temperature {day.temp_max:.1f}°C exceeds Rice Aman limit {t.temp_max:.0f}°C"
        )
    if day.temp_min < t.temp_min:
        triggers.append(
            f"Min temperature {day.temp_min:.1f}°C below Rice Aman limit {t.temp_min:.0f}°C"
        )
    # Relative humidity swings ~25 points within a day, so each bound is
    # tested against the statistic it was derived from: the floor comes from
    # the season's daily minima, the ceiling from its daily maxima. Testing
    # the daily maximum against the floor made every humid day read as dry.
    if day.humidity_min < t.humidity_min:
        triggers.append(
            f"Humidity fell to {day.humidity_min:.0f}%, below the Rice Aman "
            f"daily low of {t.humidity_min:.0f}%"
        )
    elif day.humidity_max > t.humidity_max:
        triggers.append(
            f"Humidity peaked at {day.humidity_max:.0f}%, above the Rice Aman "
            f"daily high of {t.humidity_max:.0f}%"
        )
    if day.rain_mm >= t.rain_critical:
        triggers.append(f"Critical rainfall {day.rain_mm:.1f} mm/day")
    elif day.rain_mm >= t.rain_medium:
        triggers.append(f"High rainfall {day.rain_mm:.1f} mm/day")
    if day.wind_kmh > t.wind_max:
        triggers.append(
            f"Wind {day.wind_kmh:.0f} km/h exceeds Rice Aman limit {t.wind_max:.0f} km/h"
        )

    return triggers


# ── Disease detection (auto-generated from BAMIS disease risk conditions) ────


def detect_bacterial_leaf_blight(day: DailyForecastPoint) -> str | None:
    temp_mean = (day.temp_min + day.temp_max) / 2.0
    if (
        (28.0 <= temp_mean <= 30.0)
        and (80.0 <= day.humidity_max <= 90.0)
        and (day.rain_mm >= 30.0)
    ):
        return "Bacterial Leaf Blight risk: weather conditions match threshold"
    return None


def detect_sheath_blight(day: DailyForecastPoint) -> str | None:
    temp_mean = (day.temp_min + day.temp_max) / 2.0
    if 28.0 <= temp_mean <= 32.0:
        return "Sheath Blight risk: weather conditions match threshold"
    return None


def detect_blast(day: DailyForecastPoint) -> str | None:
    if (16.0 <= day.temp_min <= 20.0) and (day.humidity_max >= 90.0):
        return "Blast risk: weather conditions match threshold"
    return None


def detect_sheath_rot(day: DailyForecastPoint) -> str | None:
    temp_mean = (day.temp_min + day.temp_max) / 2.0
    if (25.0 <= temp_mean <= 28.0) and (day.humidity_max >= 90.0):
        return "Sheath Rot risk: weather conditions match threshold"
    return None


def detect_stem_borer(day: DailyForecastPoint) -> str | None:
    if (day.temp_min >= 20.3) and (day.humidity_max >= 84.0):
        return "Stem Borer risk: weather conditions match threshold"
    return None


def detect_leaf_roller(day: DailyForecastPoint) -> str | None:
    if (32.0 <= day.temp_max <= 33.0) and (92.0 <= day.humidity_max <= 95.0):
        return "Leaf Roller risk: weather conditions match threshold"
    return None


def detect_brown_plant_hopper(day: DailyForecastPoint) -> str | None:
    if (
        (day.temp_max >= 32.0)
        and (80.0 <= day.humidity_max <= 90.0)
        and (day.rain_mm <= 75.0)
    ):
        return "Brown Plant Hopper risk: weather conditions match threshold"
    return None


def detect_rice_bug(day: DailyForecastPoint) -> str | None:
    if (day.temp_max >= 31.9) and (day.humidity_max >= 93.9) and (day.rain_mm <= 40.9):
        return "Rice Bug risk: weather conditions match threshold"
    return None


def get_disease_risks(day: DailyForecastPoint) -> list[str]:
    """Return active disease risk strings for one forecast day."""
    risks: list[str] = []
    r = detect_bacterial_leaf_blight(day)
    if r:
        risks.append(r)
    r = detect_sheath_blight(day)
    if r:
        risks.append(r)
    r = detect_blast(day)
    if r:
        risks.append(r)
    r = detect_sheath_rot(day)
    if r:
        risks.append(r)
    r = detect_stem_borer(day)
    if r:
        risks.append(r)
    r = detect_leaf_roller(day)
    if r:
        risks.append(r)
    r = detect_brown_plant_hopper(day)
    if r:
        risks.append(r)
    r = detect_rice_bug(day)
    if r:
        risks.append(r)
    return risks


def classify_tier(
    triggers: list[str], flood_confirmed: bool = False
) -> tuple[int, str]:
    """Map trigger list to severity tier (0=Normal … 4=Emergency)."""
    severe = 0
    advisory = 0
    for trig in triggers:
        t_lower = trig.lower()
        if "critical rainfall" in t_lower or (
            "temperature" in t_lower or "wind" in t_lower or "high rainfall" in t_lower
        ):
            severe += 1
        else:
            advisory += 1

    if severe == 0 and advisory == 0:
        tier = 0
    elif severe == 0:
        tier = 1
    elif severe == 1:
        tier = 2
    else:
        tier = 3

    if flood_confirmed and tier >= 3:
        tier = min(tier + 1, 4)
    return tier, _TIER_LABELS[tier]


def build_push_message(assessment: dict) -> str:
    location = assessment["location"]
    forecast_date = assessment.get("forecast_date", "")
    tier = assessment.get("tier", 0)
    triggers = assessment.get("triggers", [])
    disease_risks = assessment.get("disease_risks", [])

    if tier >= 4:
        return (
            f"Rice Aman emergency for {location}: severe weather and flood risk "
            f"expected on {forecast_date}. Protect fields now."
        )
    if triggers:
        return (
            f"Rice Aman warning for {location} on {forecast_date}: "
            f"{triggers[0]}. Take protective action today."
        )
    if disease_risks:
        return (
            f"Rice Aman advisory for {location}: "
            f"{disease_risks[0]}. Monitor field conditions closely."
        )
    return f"Rice Aman weather update for {location}: monitor conditions."
