# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

ARG IMAGE_REPO=opea
ARG BASE_TAG=latest
FROM $IMAGE_REPO/comps-base:$BASE_TAG

WORKDIR /app

ENV PYTHONPATH=/app/GenAIComps:${PYTHONPATH}

COPY ./GenAIComps /app/GenAIComps/
COPY ./ChatQnA /app/ChatQnA/

RUN pip install langdetect
RUN pip install transformers

ENTRYPOINT ["bash", "/app/ChatQnA/entrypoint.sh"]

# ENTRYPOINT ["bash", "/home/user/1.3/ChatQnA/entrypoint.sh"]
