// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2D2TfCpVn-Fopzjkcvz4uNAp1f1FrKSg',
    appId: '1:1041668070412:web:4b4971ac7939dd1ee3e229',
    messagingSenderId: '1041668070412',
    projectId: 'bangladesh-ews',
    authDomain: 'bangladesh-ews.firebaseapp.com',
    storageBucket: 'bangladesh-ews.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwhq-OL6x8jswuzTaXVDHqtSn37K_YRh4',
    appId: '1:1041668070412:android:b98297142ffc10ede3e229',
    messagingSenderId: '1041668070412',
    projectId: 'bangladesh-ews',
    storageBucket: 'bangladesh-ews.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmUokQ8UszurtNtZjOVwFEzwK_CxLzbQQ',
    appId: '1:1041668070412:ios:032686e41fc8bcdbe3e229',
    messagingSenderId: '1041668070412',
    projectId: 'bangladesh-ews',
    storageBucket: 'bangladesh-ews.firebasestorage.app',
    iosBundleId: 'com.example.genieAiMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmUokQ8UszurtNtZjOVwFEzwK_CxLzbQQ',
    appId: '1:1041668070412:ios:032686e41fc8bcdbe3e229',
    messagingSenderId: '1041668070412',
    projectId: 'bangladesh-ews',
    storageBucket: 'bangladesh-ews.firebasestorage.app',
    iosBundleId: 'com.example.genieAiMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2D2TfCpVn-Fopzjkcvz4uNAp1f1FrKSg',
    appId: '1:1041668070412:web:627f2b52b32e2636e3e229',
    messagingSenderId: '1041668070412',
    projectId: 'bangladesh-ews',
    authDomain: 'bangladesh-ews.firebaseapp.com',
    storageBucket: 'bangladesh-ews.firebasestorage.app',
  );
}
