  [31morigin/Agriculture-AgriConnect-branch[m
  [31morigin/Agriculture-AgriPivot-branch[m
  [31morigin/Agriculture-Inko-branch[m
  [31morigin/Climate-Barind-branch[m
  [31morigin/Climate-CHP-Team-branch[m
  [31morigin/Climate-PolisenseAI-branch[m
  [31morigin/HEAD[m -> origin/main
  [31morigin/Health-AminaCare-branch[m
  [31morigin/Health-Innov8AI-branch[m
  [31morigin/Health-YoungAI-Leaders-branch[m
  [31morigin/align-tooling[m
  [31morigin/backend-node-cleanup[m
  [31morigin/deployment-stabilization[m
  [31morigin/document-repo-cleanup[m
  [31morigin/el-salvador[m
  [31morigin/feature/doc-repo[m
  [31morigin/feature/epic2-backend[m
  [31morigin/feature/gpu[m
  [31morigin/feature/keycloak-idp-integration[m
  [31morigin/genie-ai-overlay-cleanup[m
  [31morigin/main[m
  [31morigin/miaomioa.song-main-patch-14670[m
  [31morigin/miaomioa.song-main-patch-18386[m
  [31morigin/miaomioa.song-main-patch-18695[m
  [31morigin/miaomioa.song-main-patch-19225[m
  [31morigin/miaomioa.song-main-patch-28996[m
  [31morigin/miaomioa.song-main-patch-30943[m
  [31morigin/miaomioa.song-main-patch-48406[m
  [31morigin/miaomioa.song-main-patch-62771[m
  [31morigin/miaomioa.song-main-patch-84771[m
  [31morigin/miaomioa.song-main-patch-93651[m
  [31morigin/miaomioa.song-main-patch-94401[m
  [31morigin/revert-1d95538b[m
  [31morigin/revert-6c63c43b[m
  [31morigin/vue-app-cleanup[m
