FROM node:22.14.0-alpine AS build

ARG VUE_APP_API_URL
ENV VUE_APP_API_URL=$VUE_APP_API_URL

ARG VUE_APP_CSP_CONNECT_SRC
ENV VUE_APP_CSP_CONNECT_SRC=$VUE_APP_CSP_CONNECT_SRC

ARG VUE_PROXY_HOST
ENV VUE_PROXY_HOST=$VUE_PROXY_HOST

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build  # Builds to /app/dist

# Production stage
FROM node:22.14.0-alpine

ARG VUE_APP_CSP_CONNECT_SRC
ENV VUE_APP_CSP_CONNECT_SRC=$VUE_APP_CSP_CONNECT_SRC

WORKDIR /app

COPY --from=build /app/dist /app/dist
COPY --from=build /app/server.js /app/server.js

EXPOSE 8090

CMD ["node", "server.js"]