parent=keycloak.v2

styles=css/genie.css css/dark.css

darkMode=true
kcDarkModeClass=pf-v5-theme-dark
contentHashPattern=assets/.*

logo=/img/logo.png
title=GENIE.AI Administration Console
description=GENIE.AI Administration Console
