parent=genie
styles=css/el-salvador.css css/dark.css
darkMode=true
kcDarkModeClass=pf-v5-theme-dark
contentHashPattern=assets/.*
logo=/img/logo.png
title=AgroGenio Administration Console
description=AgroGenio Administration Console — El Salvador
