#!/usr/bin/env bash
# Generates requirements.in for the dataprep image from the pinned OPEA tag's
# requirements.txt, applying the same patches the legacy fix_dependencies.sh
# applied at build time, plus the overlay-specific extras and the explicit
# docling-core pin (see GitLab issue #834: docling-core>=2.83.0 removed
# legacy_doc.BaseText, which docling==2.30.0 imports at startup).
#
# Run this when bumping OPEA_VERSION in the Dockerfile. Then run
# `make lock-dataprep` to regenerate requirements.lock from this .in.
#
# Usage: ./generate-requirements-in.sh [OPEA_TAG]  (default: v1.3)
#
# === OPEA v1.4+ BUMP — THIS SCRIPT BECOMES REDUNDANT ===
# OPEA v1.4+ ships its own requirements.in + uv-compiled requirements-cpu.txt
# (with hashes, docling-core pinned correctly). On bumping OPEA past v1.3, this
# script, requirements.in, requirements.lock, and the docling-core pin can be
# deleted in favor of OPEA's compiled lock. See deferred-work.md (Initiative:
# issue-834) for the full retirement checklist. KEEP smoke:dataprep-arango.
set -euo pipefail

OPEA_TAG="${1:-v1.3}"
SRC_URL="https://raw.githubusercontent.com/opea-project/GenAIComps/${OPEA_TAG}/comps/dataprep/src/requirements.txt"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="${SCRIPT_DIR}/../requirements.in"

echo "Fetching OPEA ${OPEA_TAG} dataprep requirements from ${SRC_URL}"
TMP="$(mktemp)"
curl -fsSL "${SRC_URL}" -o "${TMP}"

# Patches (parity with legacy build-patches/fix_dependencies.sh + Dockerfile sed):
#   - unstructured[all-docs] -> unstructured (drop heavy extra, image-size)
#   - drop pyspark (image "no space left on device")
#   - drop graspologic (conflicting, unused by GENIE dataprep path)
#   - drop openai-whisper (audio transcription; unused by GENIE dataprep path,
#     and its sdist build needs pkg_resources not declared as a build dep —
#     blocks uv pip compile. OPEA keeps it for its own audio ingest path.)
#   - psycopg2 -> psycopg2-binary (avoid source compile)
sed -i 's/unstructured\[all-docs\]/unstructured/' "${TMP}"
sed -i '/^pyspark==/d' "${TMP}"
sed -i '/^graspologic==/d' "${TMP}"
sed -i '/^openai-whisper==/d' "${TMP}"
sed -i 's/^psycopg2==/psycopg2-binary==/' "${TMP}"

# opencv-python -> opencv-python-headless (server image has no display; the two
# packages conflict — both provide cv2 — and cannot coexist in a hash-pinned lock).
sed -i 's/^opencv-python==/opencv-python-headless==/' "${TMP}"

{
  echo "# AUTO-GENERATED by scripts/generate-requirements-in.sh from OPEA ${OPEA_TAG}."
  echo "# Do not hand-edit — re-run the generator on OPEA bumps, and add overrides below."
  echo "# Source: comps/dataprep/src/requirements.txt @ OPEA ${OPEA_TAG}, patched for GENIE.AI."
  echo ""
  cat "${TMP}"
  rm -f "${TMP}"

  echo ""
  echo "# === Overlay-specific dependencies (genie-ai-overlay/dataprep) ==="
  echo "rank_bm25"
  echo "hf_xet"
  echo "python-jose[cryptography]"
  echo "aiohttp"

  echo ""
  echo "# === OpenTelemetry instrumentation (distributed tracing) ==="
  echo "opentelemetry-instrumentation-fastapi>=0.43b0"
  echo "opentelemetry-instrumentation-aiohttp-client>=0.43b0"
  echo "opentelemetry-instrumentation-requests>=0.43b0"
  echo "opentelemetry-exporter-otlp-proto-http>=1.22"

  echo ""
  echo "# === Issue #834: pin docling-core below the legacy_doc removal ==="
  echo "# docling==2.30.0 imports docling_core.types.legacy_doc.base.BaseText,"
  echo "# which was deleted in docling-core 2.83.0 (2026-06-18). The declared"
  echo "# range docling-core>=2.26.0,<3.0.0 lets pip pick the breaking version."
  echo "# 2.82.0 is the last release with a functional legacy_doc.BaseText."
  echo "docling-core==2.82.0"
} > "${OUT}"

echo "Wrote ${OUT}"
echo "Next: make lock-dataprep"
