"""
Eggplant risk evaluator.
Auto-generated by build_crop_profiles_pipeline.py — do not edit manually.
Uses DayForecast dicts as stored in ArangoDB weather_forecasts collection.
"""

from __future__ import annotations

from dataclasses import dataclass

from app.crops.eggplant.profile import EggplantThresholds

_TIER_LABELS = {0: "Normal", 1: "Advisory", 2: "Warning", 3: "Severe", 4: "Emergency"}


@dataclass
class DailyForecastPoint:
    date: str
    temp_min: float
    temp_max: float
    humidity_max: float
    humidity_min: float
    rain_mm: float
    wind_kmh: float
    source: str


def to_point_from_dict(day: dict, source: str) -> DailyForecastPoint:
    """Convert a raw ArangoDB DayForecast dict to DailyForecastPoint."""
    # `humidity` is the daily maximum. Older documents and the BMD source
    # carry only that one value; fall back to it so a missing daily minimum
    # cannot silently read as 0% and fire a dryness trigger.
    return DailyForecastPoint(
        date=day["date"],
        temp_min=day["temperature"]["min"],
        temp_max=day["temperature"]["max"],
        humidity_max=day["humidity"],
        humidity_min=day.get("humidity_min") or day["humidity"],
        rain_mm=day["precipitation"]["value"],
        wind_kmh=day["wind"]["speed"],
        source=source,
    )


def evaluate_eggplant_day(day: DailyForecastPoint, t: EggplantThresholds) -> list[str]:
    """Return threshold breaches for one forecast day."""
    triggers: list[str] = []

    if day.temp_max > t.temp_max:
        triggers.append(
            f"Max temperature {day.temp_max:.1f}°C exceeds Eggplant limit {t.temp_max:.0f}°C"
        )
    if day.temp_min < t.temp_min:
        triggers.append(
            f"Min temperature {day.temp_min:.1f}°C below Eggplant limit {t.temp_min:.0f}°C"
        )
    # Relative humidity swings ~25 points within a day, so each bound is
    # tested against the statistic it was derived from: the floor comes from
    # the season's daily minima, the ceiling from its daily maxima. Testing
    # the daily maximum against the floor made every humid day read as dry.
    if day.humidity_min < t.humidity_min:
        triggers.append(
            f"Humidity fell to {day.humidity_min:.0f}%, below the Eggplant "
            f"daily low of {t.humidity_min:.0f}%"
        )
    elif day.humidity_max > t.humidity_max:
        triggers.append(
            f"Humidity peaked at {day.humidity_max:.0f}%, above the Eggplant "
            f"daily high of {t.humidity_max:.0f}%"
        )
    if day.rain_mm >= t.rain_critical:
        triggers.append(f"Critical rainfall {day.rain_mm:.1f} mm/day")
    elif day.rain_mm >= t.rain_medium:
        triggers.append(f"High rainfall {day.rain_mm:.1f} mm/day")
    if day.wind_kmh > t.wind_max:
        triggers.append(
            f"Wind {day.wind_kmh:.0f} km/h exceeds Eggplant limit {t.wind_max:.0f} km/h"
        )

    return triggers


# ── Disease detection (auto-generated from BAMIS disease risk conditions) ────


def detect_shoot_and_fruit_borer(day: DailyForecastPoint) -> str | None:
    temp_mean = (day.temp_min + day.temp_max) / 2.0
    if (24.0 <= temp_mean <= 30.0) and (55.0 <= day.humidity_max <= 75.0):
        return "Shoot And Fruit Borer risk: weather conditions match threshold"
    return None


def detect_leaf_hopper_jassid_thrips(day: DailyForecastPoint) -> str | None:
    temp_mean = (day.temp_min + day.temp_max) / 2.0
    if (22.0 <= temp_mean <= 30.0) and (60.0 <= day.humidity_max <= 65.0):
        return "Leaf Hopper Jassid Thrips risk: weather conditions match threshold"
    return None


def detect_epilachna_beetle(day: DailyForecastPoint) -> str | None:
    temp_mean = (day.temp_min + day.temp_max) / 2.0
    if (25.0 <= temp_mean <= 30.0) and (55.0 <= day.humidity_max <= 65.0):
        return "Epilachna Beetle risk: weather conditions match threshold"
    return None


def detect_red_mites(day: DailyForecastPoint) -> str | None:
    temp_mean = (day.temp_min + day.temp_max) / 2.0
    if (15.0 <= temp_mean <= 26.0) and (60.0 <= day.humidity_max <= 70.0):
        return "Red Mites risk: weather conditions match threshold"
    return None


def detect_white_fly(day: DailyForecastPoint) -> str | None:
    temp_mean = (day.temp_min + day.temp_max) / 2.0
    if (22.0 <= temp_mean <= 32.0) and (55.0 <= day.humidity_max <= 75.0):
        return "White Fly risk: weather conditions match threshold"
    return None


def detect_wilting(day: DailyForecastPoint) -> str | None:
    temp_mean = (day.temp_min + day.temp_max) / 2.0
    if (25.0 <= temp_mean <= 30.0) and (50.0 <= day.humidity_max <= 80.0):
        return "Wilting risk: weather conditions match threshold"
    return None


def detect_foot_rot_collar_rot_disease(day: DailyForecastPoint) -> str | None:
    temp_mean = (day.temp_min + day.temp_max) / 2.0
    if (24.0 <= temp_mean <= 30.0) and (70.0 <= day.humidity_max <= 80.0):
        return "Foot Rot Collar Rot Disease risk: weather conditions match threshold"
    return None


def detect_fruit_rot(day: DailyForecastPoint) -> str | None:
    temp_mean = (day.temp_min + day.temp_max) / 2.0
    if (28.0 <= temp_mean <= 32.0) and (55.0 <= day.humidity_max <= 75.0):
        return "Fruit Rot risk: weather conditions match threshold"
    return None


def get_disease_risks(day: DailyForecastPoint) -> list[str]:
    """Return active disease risk strings for one forecast day."""
    risks: list[str] = []
    r = detect_shoot_and_fruit_borer(day)
    if r:
        risks.append(r)
    r = detect_leaf_hopper_jassid_thrips(day)
    if r:
        risks.append(r)
    r = detect_epilachna_beetle(day)
    if r:
        risks.append(r)
    r = detect_red_mites(day)
    if r:
        risks.append(r)
    r = detect_white_fly(day)
    if r:
        risks.append(r)
    r = detect_wilting(day)
    if r:
        risks.append(r)
    r = detect_foot_rot_collar_rot_disease(day)
    if r:
        risks.append(r)
    r = detect_fruit_rot(day)
    if r:
        risks.append(r)
    return risks


def classify_tier(
    triggers: list[str], flood_confirmed: bool = False
) -> tuple[int, str]:
    """Map trigger list to severity tier (0=Normal … 4=Emergency)."""
    severe = 0
    advisory = 0
    for trig in triggers:
        t_lower = trig.lower()
        if "critical rainfall" in t_lower or (
            "temperature" in t_lower or "wind" in t_lower or "high rainfall" in t_lower
        ):
            severe += 1
        else:
            advisory += 1

    if severe == 0 and advisory == 0:
        tier = 0
    elif severe == 0:
        tier = 1
    elif severe == 1:
        tier = 2
    else:
        tier = 3

    if flood_confirmed and tier >= 3:
        tier = min(tier + 1, 4)
    return tier, _TIER_LABELS[tier]


def build_push_message(assessment: dict) -> str:
    location = assessment["location"]
    forecast_date = assessment.get("forecast_date", "")
    tier = assessment.get("tier", 0)
    triggers = assessment.get("triggers", [])
    disease_risks = assessment.get("disease_risks", [])

    if tier >= 4:
        return (
            f"Eggplant emergency for {location}: severe weather and flood risk "
            f"expected on {forecast_date}. Protect fields now."
        )
    if triggers:
        return (
            f"Eggplant warning for {location} on {forecast_date}: "
            f"{triggers[0]}. Take protective action today."
        )
    if disease_risks:
        return (
            f"Eggplant advisory for {location}: "
            f"{disease_risks[0]}. Monitor field conditions closely."
        )
    return f"Eggplant weather update for {location}: monitor conditions."
