
# ========= GENERAL =========
LOGFLAG=true
no_proxy=noproxy
http_proxy=
https_proxy=

# ========= AUTH KEYS =========
HUGGINGFACEHUB_API_TOKEN=YOUR_HUGGINGFACEHUB_API_TOKEN
VLLM_API_KEY=YOUR_VLLM_API_KEY


# ========= ARANGODB =========
ARANGO_USERNAME=YOUR_ARANGO_USERNAME
ARANGO_PASSWORD=YOUR_ARANGO_PASSWORD
ARANGO_DB_NAME=YOUR_ARANGO_DB_NAME

# ========= DATAPREP =========
DATAPREP_CHUNK_SIZE=500
DATAPREP_CHUNK_OVERLAP=50
DATAPREP_ARANGO_INSERT_ASYNC=false
DATAPREP_ARANGO_USE_GRAPH_NAME=true
DATAPREP_NODE_PROPERTIES=
DATAPREP_RELATIONSHIP_PROPERTIES=
DATAPREP_OPENAI_CHAT_ENABLED=true
DATAPREP_OPENAI_EMBED_ENABLED=true
DATAPREP_EMBED_NODES=true
DATAPREP_EMBED_RELATIONSHIPS=true
DATAPREP_EMBED_SOURCE_DOCUMENTS=true
DATAPREP_ARANGO_GRAPH_NAME=YOUR_DATAPREP_GRAPH_NAME

# ========= RETRIEVER =========
RETRIEVER_ARANGO_GRAPH_NAME=YOUR_RETRIEVER_GRAPH_NAME
RETRIEVER_ARANGO_SEARCH_START=node # node | edge | chunk
RETRIEVER_ARANGO_SEARCH_MODE=hybrid
RETRIEVER_ARANGO_TRAVERSAL_ENABLED=true
RETRIEVER_ARANGO_TRAVERSAL_MAX_DEPTH=3
RETRIEVER_ARANGO_USE_APPROX_SEARCH=false
RETRIEVER_SUMMARIZER_ENABLED=false
RETRIEVER_OPENAI_CHAT_ENABLED=true
RETRIEVER_OPENAI_EMBED_ENABLED=true
RETRIEVER_OPENAI_EMBED_MODEL=text-embedding-3-small

# ========= VLLM =========
VLLM_ENDPOINT=http://vllm:80

# ========= MODELS =========
EMBEDDING_MODEL_ID=BAAI/bge-base-en-v1.5
RERANKER_MODEL_ID=BAAI/bge-reranker-v2-m3 #BAAI/bge-reranker-base
LLM_MODEL_ID=meta-llama/Llama-3.3-70B-Instruct
TEI_EMBED_MODEL=BAAI/bge-base-en-v1.5

# ========= TELEMETRY (optional) =========
JAEGER_IP=127.0.0.1
OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=grpc://127.0.0.1:4317
TELEMETRY_ENDPOINT=http://127.0.0.1:4318/v1/traces
