---
- name: Restart gitlab-runner
  ansible.builtin.systemd:
    name: gitlab-runner
    state: restarted

- name: Reload udev rules
  ansible.builtin.command:
    cmd: udevadm control --reload-rules && udevadm trigger --name-match=kvm
  changed_when: true
