version: '3.8'

volumes:
  redis_data:
services:
  frontend:
    build: ./gov-chat-frontend
    restart: unless-stopped
    ports:
      - "8090:8090"
    environment:
      - NODE_ENV=production
      - VUE_APP_API_URL=https://e2e-82-109.ssdcloudindia.net:443/api
      - VUE_APP_CSP_CONNECT_SRC='self'' http://localhost:3000 ws://localhost:8090 wss://localhost:8090 wss://genie-ai.itu.int:443 ws://e2e-g2-109.ssdcloudindia.net:443 wss://e2e-g2-109.ssdcloudindia.net:443 https://genie-ai.itu.int https://e2e-g2-109.ssdcloudindia.net'
    depends_on:
      - backend
    networks:
      - chatqna_default

  redis-cache:
    image: redis:7-alpine
    container_name: redis-cache
    restart: unless-stopped
    ports:
      - "6379:6379" # Optional: Expose on host for debugging
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - chatqna_default

  backend:
    build:
      context: .
      dockerfile: gov-chat-backend/Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./database_backups:/app/database_backups
      - ./logs:/app/logs
      - ./data:/app/data
      - ./gov-chat-backend/Uploads:/app/Uploads
    environment:
      - TRANSLATION_THREADS=4
      - TRANSLATION_BATCHES=5
      - TRANSLATION_CACHE=on
      - TRANSLATION_CACHE_PATH=/cache/translations
      - NODE_ENV=production
      - PORT=3000
      - API_PREFIX=/api
      - UPLOAD_DIR=./Uploads
      - MAX_FILE_SIZE=5242880
      - SESSION_SECRET=${SESSION_SECRET:-default-session-secret}
      - SESSION_EXPIRATION_TIME=1800000
      - CORS_ORIGIN=https://e2e-82-109.ssdcloudindia.net/
      - EMAIL_HOST=smtp.itu.ch
      - EMAIL_PORT=587
      - EMAIL_SECURE=false
      - EMAIL_USER=genie-ai
      - EMAIL_PASSWORD=gLp+Ek)Vf)
      - EMAIL_FROM=noreply@genie-ai.itu.int
      - APP_NAME=Genie AI
      - FRONTEND_URL=https://genie-ai.itu.int/
      - ARANGO_URL=http://arango-vector-db:8529
      - ARANGO_DB=node-services
      - ARANGO_USER=root
      - ARANGO_PASSWORD=test
      - BACKUP_DIR=./database_backups
      - MAX_BACKUPS=5
      - BACKUP_FORMAT=json
      - JWT_SECRET=${JWT_SECRET:-default-jwt-secret}
      - JWT_EXPIRES_IN=24h
      - LOG_LEVEL=debug
      - OPEA_HOST=e2e-109-198
      - OPEA_PORT=8888
      - CONTEXT_OPTION=conversation-with-context-labels
      - CORS_ALLOWED_ORIGINS=http://localhost:8090,https://localhost:8090,https://genie-ai.itu.int,/^https?:\/\/.*\.ssdcloudindia\.net$$/
      - CSP_CONNECT_SRC='self' http://localhost:3000 http://localhost:8090 ws://localhost:8090 wss://*.ssdcloudindia.net *.ssdcloudindia.net https://api.open-meteo.com https://ipapi.co https://nominatim.openstreetmap.org wss://genie-ai.itu.int:443'
      - TRANSLATION_CACHE_HOST=redis-cache
      - TRANSLATION_CACHE_PORT=6379
    env_file:
      - ./gov-chat-backend/.env
    depends_on:
      redis-cache:
        condition: service_healthy
    networks:
      - chatqna_default
  
  document-repository:
    build:
      context: .
      dockerfile: document-repository/Dockerfile
    container_name: doc-repo-dev
    environment:
      - ARANGO_URL=http://arango-vector-db:8529
      - ARANGO_PASSWORD=test
      - DOCUMENT_INGESTION_LANGUAGE=en
    depends_on:
      - clamav
    ports:
      - "3001:3001"
    networks:
      - chatqna_default
    volumes:
      - ./document-repository:/app
      - ./logs:/app/logs
      - ./document-repository/scripts/clamav-node.sh:/app/clamav-node.sh
      # - ./document-repository/uploads:/app/uploads
  
  clamav:
    image: mkodockx/docker-clamav:alpine
    container_name: clamav
    ports:
      - "3310:3310" # ClamAV daemon port
    networks:
      - chatqna_default

networks:
  chatqna_default:
    external: true
