version: '3.8'

services:
  frontend:
    build: ./gov-chat-frontend
    restart: unless-stopped
    ports:
      - "8090:8090"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - chatqna_default

  backend:
    build:
      context: .  # Use ~/chat-ui-vue-app/ as build context
      dockerfile: gov-chat-backend/Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./database_backups:/app/database_backups
      - ./logs:/app/logs
    environment:
      # Server Configuration
      - NODE_ENV=production
      - PORT=3000
      - API_PREFIX=/api
      
      # File Upload Configuration
      - UPLOAD_DIR=./uploads
      - MAX_FILE_SIZE=5242880
      
      # Session Configuration
      - SESSION_SECRET=${SESSION_SECRET}
      - SESSION_EXPIRATION_TIME=1800000
      
      # CORS Configuration
      - CORS_ORIGIN=https://e2e-82-109.ssdcloudindia.net/
      
      # Email configuration
      - EMAIL_HOST=in-V3.mailjet.com
      - EMAIL_PORT=587
      - EMAIL_SECURE=false
      - EMAIL_USER=187ad3288090609e6e282b07f359acd4
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_FROM=fordendk@gmail.com
      - APP_NAME=Huduma AI
      - FRONTEND_URL=https://e2e-82-109.ssdcloudindia.net/
      
      # Database connection setup
      - ARANGO_URL=http://arango-vector-db:8529
      - ARANGO_DB=node-services
      - ARANGO_USER=root
      - ARANGO_PASSWORD=${ARANGO_PASSWORD}
      
      # Database backups
      - BACKUP_DIR=./database_backups
      - MAX_BACKUPS=5
      - BACKUP_FORMAT=json
      
      # JWT Configuration
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=24h
      
      # Logger config
      - LOG_LEVEL=debug
    env_file:
      - ./gov-chat-backend/.env
    networks:
      - chatqna_default

networks:
  chatqna_default:
    external: true
