// source: tempopb/trace.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var opentelemetry_proto_trace_v1_trace_pb = require('../opentelemetry/proto/trace/v1/trace_pb.js');
goog.object.extend(proto, opentelemetry_proto_trace_v1_trace_pb);
goog.exportSymbol('proto.tempopb.PartialStatus', null, global);
goog.exportSymbol('proto.tempopb.Trace', null, global);
goog.exportSymbol('proto.tempopb.TraceByIDResponse', null, global);
goog.exportSymbol('proto.tempopb.TraceMetrics', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tempopb.TraceMetrics = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tempopb.TraceMetrics, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tempopb.TraceMetrics.displayName = 'proto.tempopb.TraceMetrics';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tempopb.Trace = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.tempopb.Trace.repeatedFields_, null);
};
goog.inherits(proto.tempopb.Trace, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tempopb.Trace.displayName = 'proto.tempopb.Trace';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tempopb.TraceByIDResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tempopb.TraceByIDResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tempopb.TraceByIDResponse.displayName = 'proto.tempopb.TraceByIDResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tempopb.TraceMetrics.prototype.toObject = function(opt_includeInstance) {
  return proto.tempopb.TraceMetrics.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tempopb.TraceMetrics} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tempopb.TraceMetrics.toObject = function(includeInstance, msg) {
  var f, obj = {
    tracecounttotal: jspb.Message.getFieldWithDefault(msg, 1, 0),
    tracecountexemplar: jspb.Message.getFieldWithDefault(msg, 2, 0),
    spanspertracecount: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tempopb.TraceMetrics}
 */
proto.tempopb.TraceMetrics.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tempopb.TraceMetrics;
  return proto.tempopb.TraceMetrics.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tempopb.TraceMetrics} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tempopb.TraceMetrics}
 */
proto.tempopb.TraceMetrics.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTracecounttotal(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTracecountexemplar(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setSpanspertracecount(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tempopb.TraceMetrics.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tempopb.TraceMetrics.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tempopb.TraceMetrics} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tempopb.TraceMetrics.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTracecounttotal();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getTracecountexemplar();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getSpanspertracecount();
  if (f !== 0) {
    writer.writeUint64(
      3,
      f
    );
  }
};


/**
 * optional uint64 traceCountTotal = 1;
 * @return {number}
 */
proto.tempopb.TraceMetrics.prototype.getTracecounttotal = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.tempopb.TraceMetrics} returns this
 */
proto.tempopb.TraceMetrics.prototype.setTracecounttotal = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint64 traceCountExemplar = 2;
 * @return {number}
 */
proto.tempopb.TraceMetrics.prototype.getTracecountexemplar = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.tempopb.TraceMetrics} returns this
 */
proto.tempopb.TraceMetrics.prototype.setTracecountexemplar = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint64 spansPerTraceCount = 3;
 * @return {number}
 */
proto.tempopb.TraceMetrics.prototype.getSpanspertracecount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.tempopb.TraceMetrics} returns this
 */
proto.tempopb.TraceMetrics.prototype.setSpanspertracecount = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.tempopb.Trace.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tempopb.Trace.prototype.toObject = function(opt_includeInstance) {
  return proto.tempopb.Trace.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tempopb.Trace} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tempopb.Trace.toObject = function(includeInstance, msg) {
  var f, obj = {
    resourcespansList: jspb.Message.toObjectList(msg.getResourcespansList(),
    opentelemetry_proto_trace_v1_trace_pb.ResourceSpans.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tempopb.Trace}
 */
proto.tempopb.Trace.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tempopb.Trace;
  return proto.tempopb.Trace.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tempopb.Trace} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tempopb.Trace}
 */
proto.tempopb.Trace.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new opentelemetry_proto_trace_v1_trace_pb.ResourceSpans;
      reader.readMessage(value,opentelemetry_proto_trace_v1_trace_pb.ResourceSpans.deserializeBinaryFromReader);
      msg.addResourcespans(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tempopb.Trace.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tempopb.Trace.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tempopb.Trace} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tempopb.Trace.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResourcespansList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      opentelemetry_proto_trace_v1_trace_pb.ResourceSpans.serializeBinaryToWriter
    );
  }
};


/**
 * repeated opentelemetry.proto.trace.v1.ResourceSpans resourceSpans = 1;
 * @return {!Array<!proto.opentelemetry.proto.trace.v1.ResourceSpans>}
 */
proto.tempopb.Trace.prototype.getResourcespansList = function() {
  return /** @type{!Array<!proto.opentelemetry.proto.trace.v1.ResourceSpans>} */ (
    jspb.Message.getRepeatedWrapperField(this, opentelemetry_proto_trace_v1_trace_pb.ResourceSpans, 1));
};


/**
 * @param {!Array<!proto.opentelemetry.proto.trace.v1.ResourceSpans>} value
 * @return {!proto.tempopb.Trace} returns this
*/
proto.tempopb.Trace.prototype.setResourcespansList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.opentelemetry.proto.trace.v1.ResourceSpans=} opt_value
 * @param {number=} opt_index
 * @return {!proto.opentelemetry.proto.trace.v1.ResourceSpans}
 */
proto.tempopb.Trace.prototype.addResourcespans = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.opentelemetry.proto.trace.v1.ResourceSpans, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.tempopb.Trace} returns this
 */
proto.tempopb.Trace.prototype.clearResourcespansList = function() {
  return this.setResourcespansList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tempopb.TraceByIDResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.tempopb.TraceByIDResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tempopb.TraceByIDResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tempopb.TraceByIDResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    trace: (f = msg.getTrace()) && proto.tempopb.Trace.toObject(includeInstance, f),
    metrics: (f = msg.getMetrics()) && proto.tempopb.TraceMetrics.toObject(includeInstance, f),
    status: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tempopb.TraceByIDResponse}
 */
proto.tempopb.TraceByIDResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tempopb.TraceByIDResponse;
  return proto.tempopb.TraceByIDResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tempopb.TraceByIDResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tempopb.TraceByIDResponse}
 */
proto.tempopb.TraceByIDResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.tempopb.Trace;
      reader.readMessage(value,proto.tempopb.Trace.deserializeBinaryFromReader);
      msg.setTrace(value);
      break;
    case 2:
      var value = new proto.tempopb.TraceMetrics;
      reader.readMessage(value,proto.tempopb.TraceMetrics.deserializeBinaryFromReader);
      msg.setMetrics(value);
      break;
    case 3:
      var value = /** @type {!proto.tempopb.PartialStatus} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tempopb.TraceByIDResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tempopb.TraceByIDResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tempopb.TraceByIDResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tempopb.TraceByIDResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTrace();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.tempopb.Trace.serializeBinaryToWriter
    );
  }
  f = message.getMetrics();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.tempopb.TraceMetrics.serializeBinaryToWriter
    );
  }
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
};


/**
 * optional Trace trace = 1;
 * @return {?proto.tempopb.Trace}
 */
proto.tempopb.TraceByIDResponse.prototype.getTrace = function() {
  return /** @type{?proto.tempopb.Trace} */ (
    jspb.Message.getWrapperField(this, proto.tempopb.Trace, 1));
};


/**
 * @param {?proto.tempopb.Trace|undefined} value
 * @return {!proto.tempopb.TraceByIDResponse} returns this
*/
proto.tempopb.TraceByIDResponse.prototype.setTrace = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tempopb.TraceByIDResponse} returns this
 */
proto.tempopb.TraceByIDResponse.prototype.clearTrace = function() {
  return this.setTrace(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tempopb.TraceByIDResponse.prototype.hasTrace = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional TraceMetrics metrics = 2;
 * @return {?proto.tempopb.TraceMetrics}
 */
proto.tempopb.TraceByIDResponse.prototype.getMetrics = function() {
  return /** @type{?proto.tempopb.TraceMetrics} */ (
    jspb.Message.getWrapperField(this, proto.tempopb.TraceMetrics, 2));
};


/**
 * @param {?proto.tempopb.TraceMetrics|undefined} value
 * @return {!proto.tempopb.TraceByIDResponse} returns this
*/
proto.tempopb.TraceByIDResponse.prototype.setMetrics = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tempopb.TraceByIDResponse} returns this
 */
proto.tempopb.TraceByIDResponse.prototype.clearMetrics = function() {
  return this.setMetrics(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tempopb.TraceByIDResponse.prototype.hasMetrics = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional PartialStatus status = 3;
 * @return {!proto.tempopb.PartialStatus}
 */
proto.tempopb.TraceByIDResponse.prototype.getStatus = function() {
  return /** @type {!proto.tempopb.PartialStatus} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.tempopb.PartialStatus} value
 * @return {!proto.tempopb.TraceByIDResponse} returns this
 */
proto.tempopb.TraceByIDResponse.prototype.setStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * @enum {number}
 */
proto.tempopb.PartialStatus = {
  PARTIAL_STATUS_UNSPECIFIED: 0,
  PARTIAL_STATUS_OK: 1,
  PARTIAL_STATUS_ERROR: 2
};

goog.object.extend(exports, proto.tempopb);
