apiVersion: 1

datasources:
  - name: VictoriaLogs
    type: victoriametrics-logs-datasource
    access: proxy
    url: http://victorialogs:9428
    editable: false
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: victoriatraces
          matcherRegex: "/trace_id=\"([^\"]+)\"/"
          name: TraceID
          url: "$${__value.raw}"
        - datasourceUid: victoriatraces
          matcherRegex: "/span_id=\"([^\"]+)\"/"
          name: SpanID
          url: "$${__value.raw}"
