apiVersion: 1

datasources:
  - name: VictoriaTraces
    type: tempo
    access: proxy
    url: http://tempo-proxy:10429
    uid: victoriatraces
    editable: false
    jsonData:
      search:
        type: jaeger
      traceQuery:
        maxTraces: 1000
        maxDuration: 60m
        minDuration: 0ms
        spanStartTimeAdjustment: true
