apiVersion: 1

datasources:
  - name: VictoriaTraces
    type: jaeger
    access: proxy
    url: http://victoriatraces:10428/select/jaeger
    uid: victoriatraces
    editable: false
    jsonData:
      traceQuery:
        maxTraces: 1000
        maxDuration: 60m
        minDuration: 0ms
        spanStartTimeAdjustment: true
