// en.swift
// English translations

struct EnLocale {
    static let translations: [String: Any] = [
        "brandName": "Genie AI",
        "login": [
            "appTitle": "Genie AI",
            "username": "Username",
            "password": "Password",
            "loginButton": "Login",
            "or": "or",
            "savedAccounts": "Saved Accounts",
            "loginSuccess": "Login successful",
            "loginError": "Login failed. Please check your credentials.",
            "googleLogin": "Continue with Google",
            "facebookLogin": "Continue with Facebook",
            "rememberMe": "Remember me",
            "forgotPassword": "Forgot password?",
            "noAccount": "Don't have an account?",
            "createAccount": "Create account",
            "registerNow": "Register now",
            "termsAndPolicy": "By logging in, you agree to our Terms of Service and Privacy Policy",
            "loggingIn": "Logging in...",
            "fieldsRequired": "Username and password are required",
            "invalidCredentials": "Invalid username or password",
            "tooManyAttempts": "Too many login attempts. Please try again later.",
            "loginFailed": "Login failed. Please try again."
        ],
        "register": [
            "appTitle": "Genie AI",
            "createAccount": "Create New Account",
            "username": "Username",
            "usernamePlaceholder": "Enter a username",
            "email": "Email",
            "emailPlaceholder": "Enter your email",
            "password": "Password",
            "passwordPlaceholder": "Create a password",
            "confirmPassword": "Confirm Password",
            "confirmPasswordPlaceholder": "Confirm your password",
            "acceptTerms": "I accept the",
            "termsOfService": "Terms of Service",
            "registerButton": "Create Account",
            "processing": "Processing...",
            "alreadyHaveAccount": "Already have an account?",
            "loginNow": "Log in",
            "privacyNotice": "By registering, you agree to our Terms of Service and Privacy Policy",
            "usernameMinLength": "Username must be at least 3 characters",
            "invalidEmail": "Please enter a valid email address",
            "passwordRequirements": "Password must be at least 8 characters with at least 1 number and 1 uppercase letter",
            "passwordsDoNotMatch": "Passwords do not match",
            "mustAcceptTerms": "You must accept the Terms of Service",
            "registrationFailed": "Registration failed. Please try again.",
            "usernameExists": "Username already exists",
            "emailExists": "Email already exists",
            "registrationSuccess": "Registration Successful!",
            "verificationEmailSent": "A verification email has been sent to {email}",
            "checkEmailInstructions": "Please check your email and follow the instructions to verify your account before logging in.",
            "backToLogin": "Back to Login"
        ],
        "passwordReset": [
            "appTitle": "Genie AI",
            "resetPassword": "Reset Your Password",
            "emailLabel": "Email Address",
            "emailPlaceholder": "Enter your email",
            "resetButton": "Send Reset Link",
            "processing": "Sending...",
            "rememberPassword": "Remember your password?",
            "backToLogin": "Back to Login",
            "supportMessage": "Need help? Contact our support team",
            "invalidEmail": "Please enter a valid email address",
            "resetRequestSuccess": "Password reset link has been sent to your email",
            "resetRequestFailed": "Unable to send password reset link. Please try again.",
            "checkEmail": "Please check your email for further instructions."
        ],
        "passwordResetConfirm": [
            "appTitle": "Genie AI",
            "resetPassword": "Create New Password",
            "tokenLabel": "Reset Token",
            "tokenPlaceholder": "Enter reset token",
            "validateButton": "Validate Token",
            "newPasswordLabel": "New Password",
            "newPasswordPlaceholder": "Create a new password",
            "confirmNewPasswordLabel": "Confirm New Password",
            "confirmNewPasswordPlaceholder": "Confirm your new password",
            "resetButton": "Reset Password",
            "processing": "Resetting...",
            "rememberedPassword": "Remember your password?",
            "backToLogin": "Back to Login",
            "supportMessage": "Need help? Contact our support team",
            "passwordRequirements": "Password must be at least 8 characters with at least 1 number, 1 uppercase letter, and 1 special character",
            "passwordsDoNotMatch": "Passwords do not match",
            "resetSuccess": "Your password has been successfully reset",
            "resetFailed": "Unable to reset password. Please try again."
        ],
        "nav": [
            "systemStatus": "System Status",
            "menu": "Menu",
            "userProfile": "User Profile",
            "settings": "Settings",
            "logout": "Log Out",
            "profile": "My Profile",
            "toggleSidebar": "Toggle sidebar",
            "changeLanguage": "Change language",
            "relatedDocuments": "Related Documents"
        ],
        "sidebar": [
            "governmentServices": "Knowledge Areas",
            "chatHistory": "Chat History",
            "searchPlaceholder": "Search knowledge areas...",
            "createFolder": "Create Folder",
            "editFolder": "Edit Folder",
            "folderName": "Folder Name",
            "moveChat": "Move Chat",
            "deleteChat": "Delete Chat",
            "renameChat": "Rename Chat",
            "title": "Info & Resources",
            "noChats": "No recent chats",
            "relatedDocs": "Related Documents",
            "noDocuments": "No related documents",
            "faq": "Frequently Asked Questions",
            "allChats": "All Chats",
            "folders": "Folders",
            "starred": "Starred",
            "archived": "Archived"
        ],
        "chatbot": [
            "placeholder": "Type your query here...",
            "sendButton": "Send",
            "welcomeMessage": "Welcome! How can I assist you with Kenya government services today?",
            "attachFile": "Attach File",
            "saveChat": "Save Chat",
            "newChat": "New Chat",
            "clearContext": "Clear context and start a new conversation",
            "whatCanIHelp": "How can I help you today?",
            "thinking": "Genie is thinking...",
            "exportChat": "Export Chat"
        ],
        "quickhelp": [
            "applyForID": "Apply for ID",
            "payTaxes": "Pay Taxes",
            "startBusiness": "Start Business",
            "findHealthcare": "Healthcare",
            "educationServices": "Education",
            "transportLicenses": "Transport",
            "housingPrograms": "Housing",
            "findJobs": "Find Jobs",
            "justChat": "Just Chat",
            "applyForIDUserPrompt": "I want to find out about applying for a National ID card in Kenya.",
            "payTaxesUserPrompt": "I want to ask about paying taxes or filing my KRA returns in Kenya.",
            "startBusinessUserPrompt": "I want to find out about registering a new business or company in Kenya.",
            "findHealthcareUserPrompt": "I want to ask about public healthcare facilities and insurance (NHIF/SHIF) in Kenya.",
            "educationServicesUserPrompt": "I want to find out about schools and education services in Kenya.",
            "transportLicensesUserPrompt": "I want to ask about driving licenses and NTSA services in Kenya.",
            "housingProgramsUserPrompt": "I want to find out about the Affordable Housing Program (Boma Yangu) in Kenya.",
            "findJobsUserPrompt": "I want to ask about government job opportunities and PSC applications in Kenya.",
            "justChatUserPrompt": "I want to chat generally about life in Kenya."
        ],
        "settings": [
            "title": "Settings",
            "save": "Save",
            "close": "Close",
            "display": "Display",
            "displayLanguage": "Display Language",
            "theme": "Theme",
            "themeLight": "Light",
            "themeDark": "Dark",
            "fontSize": "Font Size",
            "notifications": "Notifications",
            "emailUpdates": "Email updates",
            "soundNotifications": "Sound notifications",
            "accountManagement": "Account Management",
            "emailAddress": "Email Address",
            "password": "Password",
            "changePassword": "Change Password",
            "resetUserData": "Reset User Data",
            "deleteAccount": "Delete Account"
        ],
        "userProfile": [
            "title": "User Profile",
            "tabs": [
                "tab1": "Personal Identification Data",
                "tab2": "Civil Registration & Documentation",
                "tab3": "Address & Residency Information",
                "tab4": "Identity & Travel Documents",
                "tab5": "Health & Medical Records",
                "tab6": "Employment & Economic Data",
                "tab7": "Education & Academic Records",
                "tab8": "Financial & Tax Data",
                "tab9": "Social Security & Welfare",
                "tab10": "Criminal & Legal Records",
                "tab11": "Transportation & Mobility",
                "tab12": "Civic & Political Participation"
            ],
            "actions": [
                "cancel": "Cancel",
                "save": "Save Profile",
                "previous": "Previous",
                "next": "Next",
                "saving": "Saving..."
            ]
        ],
        "feedback": [
            "title": "Feedback",
            "button": "Feedback",
            "positive": "Positive feedback",
            "negative": "Negative feedback",
            "promptText": "Was this response helpful?",
            "placeholder": "Additional comments...",
            "submit": "Submit Feedback",
            "close": "Cancel",
            "thankYouMessage": "Thank you for your feedback!",
            "submitting": "Submitting...",
            "error": "Something went wrong. Please try again.",
            "success": "Thank you for your feedback!"
        ],
        "common": [
            "cancel": "Cancel",
            "create": "Create",
            "save": "Save",
            "move": "Move",
            "delete": "Delete",
            "ok": "OK",
            "loading": "Loading...",
            "refresh": "Refresh",
            "open": "Open",
            "done": "Done",
            "confirm": "Confirm",
            "edit": "Edit"
        ],
        "about": [
            "title": "About",
            "version": "Version",
            "description": "Genie AI is your intelligent assistant for navigating government services and information.",
            "techStack": "Tech Stack",
            "copyright": "All rights reserved."
        ]
    ]
}
