// id.swift
// Indonesian translations

struct IdLocale {
    static let translations: [String: Any] = [
  "countries": [
    "AF": "Afganistan",
    "AL": "Albania",
    "DZ": "Aljazair",
    "AD": "Andorra",
    "AO": "Angola",
    "AG": "Antigua dan Barbuda",
    "AR": "Argentina",
    "AM": "Armenia",
    "AU": "Australia",
    "AT": "Austria",
    "AZ": "Azerbaijan",
    "BS": "Bahama",
    "BH": "Bahrain",
    "BD": "Bangladesh",
    "BB": "Barbados",
    "BY": "Belarus",
    "BE": "Belgia",
    "BZ": "Belize",
    "BJ": "Benin",
    "BT": "Bhutan",
    "BO": "Bolivia",
    "BA": "Bosnia dan Herzegovina",
    "BW": "Botswana",
    "BR": "Brasil",
    "BN": "Brunei",
    "BG": "Bulgaria",
    "BF": "Burkina Faso",
    "BI": "Burundi",
    "CV": "Tanjung Verde",
    "KH": "Kamboja",
    "CM": "Kamerun",
    "CA": "Kanada",
    "CF": "Republik Afrika Tengah",
    "TD": "Chad",
    "CL": "Chili",
    "CN": "Tiongkok",
    "CO": "Kolombia",
    "KM": "Komoro",
    "CG": "Kongo",
    "CD": "Republik Demokratik Kongo",
    "CR": "Kosta Rika",
    "CI": "Pantai Gading",
    "HR": "Kroasia",
    "CU": "Kuba",
    "CY": "Siprus",
    "CZ": "Ceko",
    "DK": "Denmark",
    "DJ": "Djibouti",
    "DM": "Dominika",
    "DO": "Republik Dominika",
    "EC": "Ekuador",
    "EG": "Mesir",
    "SV": "El Salvador",
    "GQ": "Guinea Khatulistiwa",
    "ER": "Eritrea",
    "EE": "Estonia",
    "ET": "Ethiopia",
    "FJ": "Fiji",
    "FI": "Finlandia",
    "FR": "Prancis",
    "GA": "Gabon",
    "GM": "Gambia",
    "GE": "Georgia",
    "DE": "Jerman",
    "GH": "Ghana",
    "GR": "Yunani",
    "GD": "Grenada",
    "GT": "Guatemala",
    "GN": "Guinea",
    "GW": "Guinea-Bissau",
    "GY": "Guyana",
    "HT": "Haiti",
    "HN": "Honduras",
    "HU": "Hungaria",
    "IS": "Islandia",
    "IN": "India",
    "ID": "Indonesia",
    "IR": "Iran",
    "IQ": "Irak",
    "IE": "Irlandia",
    "IL": "Israel",
    "IT": "Italia",
    "JM": "Jamaika",
    "JP": "Jepang",
    "JO": "Yordania",
    "KZ": "Kazakhstan",
    "KE": "Kenya",
    "KI": "Kiribati",
    "KP": "Korea Utara",
    "KR": "Korea Selatan",
    "KW": "Kuwait",
    "KG": "Kirgizstan",
    "LA": "Laos",
    "LV": "Latvia",
    "LB": "Lebanon",
    "LS": "Lesotho",
    "LR": "Liberia",
    "LY": "Libya",
    "LI": "Liechtenstein",
    "LT": "Lituania",
    "LU": "Luksemburg",
    "MG": "Madagaskar",
    "MW": "Malawi",
    "MY": "Malaysia",
    "MV": "Maladewa",
    "ML": "Mali",
    "MT": "Malta",
    "MH": "Kepulauan Marshall",
    "MR": "Mauritania",
    "MU": "Mauritius",
    "MX": "Meksiko",
    "FM": "Mikronesia",
    "MD": "Moldova",
    "MC": "Monako",
    "MN": "Mongolia",
    "ME": "Montenegro",
    "MA": "Maroko",
    "MZ": "Mozambik",
    "MM": "Myanmar",
    "NA": "Namibia",
    "NR": "Nauru",
    "NP": "Nepal",
    "NL": "Belanda",
    "NZ": "Selandia Baru",
    "NI": "Nikaragua",
    "NE": "Niger",
    "NG": "Nigeria",
    "MK": "Makedonia Utara",
    "NO": "Norwegia",
    "OM": "Oman",
    "PK": "Pakistan",
    "PW": "Palau",
    "PS": "Palestina",
    "PA": "Panama",
    "PG": "Papua Nugini",
    "PY": "Paraguay",
    "PE": "Peru",
    "PH": "Filipina",
    "PL": "Polandia",
    "PT": "Portugal",
    "QA": "Qatar",
    "RO": "Rumania",
    "RU": "Rusia",
    "RW": "Rwanda",
    "KN": "Saint Kitts dan Nevis",
    "LC": "Saint Lucia",
    "VC": "Saint Vincent dan Grenadines",
    "WS": "Samoa",
    "SM": "San Marino",
    "ST": "Sao Tome dan Principe",
    "SA": "Arab Saudi",
    "SN": "Senegal",
    "RS": "Serbia",
    "SC": "Seychelles",
    "SL": "Sierra Leone",
    "SG": "Singapura",
    "SK": "Slowakia",
    "SI": "Slovenia",
    "SB": "Kepulauan Solomon",
    "SO": "Somalia",
    "ZA": "Afrika Selatan",
    "SS": "Sudan Selatan",
    "ES": "Spanyol",
    "LK": "Sri Lanka",
    "SD": "Sudan",
    "SR": "Suriname",
    "SZ": "Eswatini",
    "SE": "Swedia",
    "CH": "Swiss",
    "SY": "Suriah",
    "TJ": "Tajikistan",
    "TZ": "Tanzania",
    "TH": "Thailand",
    "TL": "Timor Leste",
    "TG": "Togo",
    "TO": "Tonga",
    "TT": "Trinidad dan Tobago",
    "TN": "Tunisia",
    "TR": "Turki",
    "TM": "Turkmenistan",
    "TV": "Tuvalu",
    "UG": "Uganda",
    "UA": "Ukraina",
    "AE": "Uni Emirat Arab",
    "GB": "Britania Raya",
    "US": "Amerika Serikat",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "VU": "Vanuatu",
    "VA": "Vatikan",
    "VE": "Venezuela",
    "VN": "Vietnam",
    "YE": "Yaman",
    "ZM": "Zambia",
    "ZW": "Zimbabwe"
  ],
  "verification": [
    "verifying": "Memverifikasi email Anda...",
    "success": "Email Berhasil Diverifikasi!",
    "failed": "Verifikasi Gagal",
    "accountVerified":
        "Akun Anda telah berhasil diverifikasi. Anda sekarang dapat masuk ke akun Anda.",
    "invalidLink": "Tautan verifikasi tidak valid atau telah kedaluwarsa.",
    "missingToken": "Token verifikasi hilang.",
    "generalError":
        "Terjadi kesalahan selama verifikasi. Silakan coba lagi nanti.",
    "proceedToLogin": "Lanjutkan Masuk",
    "backToLogin": "Kembali ke Masuk"
  ],
  "passwordResetConfirm": [
    "appTitle": "Genie AI",
    "resetPassword": "Buat Kata Sandi Baru",
    "tokenLabel": "Token Setel Ulang",
    "tokenPlaceholder": "Masukkan token setel ulang",
    "validateButton": "Validasi Token",
    "newPasswordLabel": "Kata Sandi Baru",
    "newPasswordPlaceholder": "Buat kata sandi baru",
    "confirmNewPasswordLabel": "Konfirmasi Kata Sandi Baru",
    "confirmNewPasswordPlaceholder": "Konfirmasi kata sandi baru Anda",
    "resetButton": "Setel Ulang Kata Sandi",
    "processing": "Mengatur ulang...",
    "rememberedPassword": "Ingat kata sandi Anda?",
    "backToLogin": "Kembali ke Masuk",
    "supportMessage": "Butuh bantuan? Hubungi tim dukungan kami",
    "passwordRequirements":
        "Kata sandi harus terdiri dari minimal 8 karakter dengan minimal 1 angka, 1 huruf besar, dan 1 karakter khusus",
    "passwordsDoNotMatch": "Kata sandi tidak cocok",
    "resetSuccess": "Kata sandi Anda telah berhasil disetel ulang",
    "resetFailed": "Tidak dapat menyetel ulang kata sandi. Silakan coba lagi.",
    "noTokenProvided": "Harap berikan token setel ulang",
    "expiredToken":
        "Token setel ulang ini telah kedaluwarsa. Silakan minta yang baru.",
    "invalidToken": "Token setel ulang tidak valid atau tidak dikenali",
    "validatingToken": "Memvalidasi token...",
    "redirecting": "Mengalihkan ke halaman masuk...",
    "passwordStrength": "Kekuatan Kata Sandi",
    "strengthLabels": [
      "veryWeak": "Sangat Lemah",
      "weak": "Lemah",
      "fair": "Cukup",
      "good": "Baik",
      "strong": "Kuat"
    ],
    "passwordSuggestions": [
      "atLeast8Chars": "Gunakan setidaknya 8 karakter",
      "addUppercase": "Tambahkan huruf besar",
      "addLowercase": "Tambahkan huruf kecil",
      "addNumbers": "Tambahkan angka",
      "addSpecialChars": "Tambahkan karakter khusus"
    ]
  ],
  "passwordReset": [
    "appTitle": "Genie AI",
    "resetPassword": "Setel Ulang Kata Sandi Anda",
    "emailLabel": "Alamat Email",
    "emailPlaceholder": "Masukkan email Anda",
    "resetButton": "Kirim Tautan Setel Ulang",
    "processing": "Mengirim...",
    "rememberPassword": "Ingat kata sandi Anda?",
    "backToLogin": "Kembali ke Masuk",
    "supportMessage": "Butuh bantuan? Hubungi tim dukungan kami",
    "invalidEmail": "Harap masukkan alamat email yang valid",
    "resetRequestSuccess":
        "Tautan setel ulang kata sandi telah dikirim ke email Anda",
    "resetRequestFailed":
        "Tidak dapat mengirim tautan setel ulang kata sandi. Silakan coba lagi.",
    "checkEmail": "Silakan periksa email Anda untuk instruksi lebih lanjut."
  ],
  "register": [
    "appTitle": "Genie AI",
    "createAccount": "Buat Akun Baru",
    "username": "Nama Pengguna",
    "usernamePlaceholder": "Masukkan nama pengguna",
    "email": "Email",
    "emailPlaceholder": "Masukkan email Anda",
    "password": "Kata Sandi",
    "passwordPlaceholder": "Buat kata sandi",
    "confirmPassword": "Konfirmasi Kata Sandi",
    "confirmPasswordPlaceholder": "Konfirmasi kata sandi Anda",
    "acceptTerms": "Saya menerima",
    "termsOfService": "Ketentuan Layanan",
    "registerButton": "Buat Akun",
    "processing": "Memproses...",
    "alreadyHaveAccount": "Sudah punya akun?",
    "loginNow": "Masuk",
    "privacyNotice":
        "Dengan mendaftar, Anda menyetujui Ketentuan Layanan dan Kebijakan Privasi kami",
    "usernameMinLength": "Nama pengguna harus terdiri dari minimal 3 karakter",
    "invalidEmail": "Harap masukkan alamat email yang valid",
    "passwordRequirements":
        "Kata sandi harus terdiri dari minimal 8 karakter dengan minimal 1 angka dan 1 huruf besar",
    "passwordsDoNotMatch": "Kata sandi tidak cocok",
    "mustAcceptTerms": "Anda harus menerima Ketentuan Layanan",
    "registrationFailed": "Pendaftaran gagal. Silakan coba lagi.",
    "usernameExists": "Nama pengguna sudah ada",
    "emailExists": "Email sudah ada",
    "registrationSuccess": "Pendaftaran Berhasil!",
    "verificationEmailSent": "Email verifikasi telah dikirim ke {email}",
    "checkEmailInstructions":
        "Harap periksa email Anda dan ikuti instruksi untuk memverifikasi akun Anda sebelum masuk.",
    "backToLogin": "Kembali ke Masuk",
    "noEmailReceived": "Tidak menerima email?",
    "resendVerification": "Kirim ulang email verifikasi",
    "verificationResent": "Email verifikasi telah dikirim ulang",
    "verificationResendFailed":
        "Gagal mengirim ulang email verifikasi. Silakan coba lagi.",
    "usernameInvalidChars":
        "Nama pengguna hanya boleh berisi huruf, angka, garis bawah, titik, dan tanda hubung",
    "networkError":
        "Kesalahan jaringan. Harap periksa koneksi Anda dan coba lagi."
  ],
  "login": [
    "appTitle": "Genie AI",
    "username": "Nama Pengguna",
    "password": "Kata Sandi",
    "loginButton": "Masuk",
    "or": "atau",
    "savedAccounts": "Akun Tersimpan",
    "loginSuccess": "Masuk berhasil",
    "loginError": "Gagal masuk. Harap periksa kredensial Anda.",
    "googleLogin": "Lanjutkan dengan Google",
    "facebookLogin": "Lanjutkan dengan Facebook",
    "rememberMe": "Ingat saya",
    "forgotPassword": "Lupa kata sandi?",
    "noAccount": "Belum punya akun?",
    "createAccount": "Buat akun",
    "registerNow": "Daftar sekarang",
    "termsAndPolicy":
        "Dengan masuk, Anda menyetujui Ketentuan Layanan dan Kebijakan Privasi kami",
    "loggingIn": "Sedang masuk...",
    "fieldsRequired": "Nama pengguna dan kata sandi wajib diisi",
    "invalidCredentials": "Nama pengguna atau kata sandi tidak valid",
    "tooManyAttempts":
        "Terlalu banyak percobaan masuk. Silakan coba lagi nanti.",
    "loginFailed": "Gagal masuk. Silakan coba lagi.",
    "oauthNotImplemented": "Masuk sosial belum diimplementasikan",
    "savedLoginNotImplemented":
        "Masuk dengan akun tersimpan belum diimplementasikan"
  ],
  "brandName": "Genie AI",
  "nav": [
    "systemStatus": "Status Sistem",
    "menu": "Menu",
    "userProfile": "Profil Pengguna",
    "settings": "Pengaturan",
    "logout": "Keluar",
    "profile": "Profil Saya",
    "toggleSidebar": "Buka/tutup bilah samping",
    "changeLanguage": "Ganti bahasa",
    "relatedDocuments": "Dokumen Terkait",
    "languages": [
      "english": "Inggris",
      "french": "Prancis",
      "swahili": "Swahili",
      "german": "Jerman",
      "spanish": "Spanyol",
      "arabic": "Arab"
    ]
  ],
  "systemStatus": [
    "title": "Status Layanan",
    "services": "Layanan",
    "operational": "Operasional",
    "degraded": "Terganggu",
    "outage": "Mati",
    "allOperational": "Semua Sistem",
    "someIssues": "Beberapa Masalah",
    "majorIssues": "Masalah Besar",
    "checking": "Memeriksa...",
    "nextDeadline": "Tenggat Waktu Berikutnya",
    "days": "hari",
    "viewDetails": "Lihat Detail"
  ],
  "services": [
    "eCitizen": "Portal eCitizen",
    "taxFiling": "Sistem Pelaporan Pajak",
    "idApplication": "Permohonan ID",
    "businessReg": "Pendaftaran Bisnis",
    "drivingLicense": "Surat Izin Mengemudi"
  ],
  "deadlines": [
    "taxFiling": "Tenggat Waktu Pelaporan Pajak",
    "businessRenewal": "Pembaruan Izin Usaha",
    "idRenewal": "Pembaruan Kartu ID",
    "vehicleRegistration": "Tenggat Waktu Pendaftaran Kendaraan"
  ],
  "sidebar": [
    "governmentServices": "Area Pengetahuan",
    "chatHistory": "Riwayat Obrolan",
    "searchPlaceholder": "Cari area pengetahuan...",
    "createFolder": "Buat Folder",
    "editFolder": "Edit Folder",
    "folderName": "Nama Folder",
    "folderNamePlaceholder": "Masukkan nama folder",
    "moveChat": "Pindahkan Obrolan",
    "moveChatTo": "Pindahkan Obrolan Ke",
    "selectFolder": "Pilih Folder",
    "deleteChat": "Hapus Obrolan",
    "deleteChatConfirm": "Apakah Anda yakin ingin menghapus obrolan ini?",
    "deleteChatWarning": "Tindakan ini tidak dapat dibatalkan.",
    "renameChat": "Ganti Nama Obrolan",
    "chatTitle": "Judul Obrolan",
    "chatTitlePlaceholder": "Masukkan judul untuk obrolan ini",
    "deleteFolder": "Hapus Folder",
    "deleteFolderConfirm": "Apakah Anda yakin ingin menghapus folder '{name}'?",
    "chatsMoveWarning":
        "Semua obrolan dalam folder ini akan dipindahkan ke folder default.",
    "weatherError": "Tidak dapat memuat data cuaca. Silakan coba lagi.",
    "weatherTitle": "Prakiraan Cuaca",
    "weatherLoading": "Memuat data cuaca...",
    "weatherLocationLoading": "Memuat lokasi...",
    "weatherErrorDefault": "Tidak dapat mengambil data cuaca.",
    "weatherGeolocationUnsupported":
        "Geolokasi tidak didukung oleh browser Anda.",
    "weatherRefresh": "Segarkan Cuaca",
    "weatherConditions": [
      "clear": "Cerah",
      "partlycloudy": "Sebagian Berawan",
      "cloudy": "Berawan",
      "overcast": "Mendung",
      "rain": "Hujan",
      "shower": "Hujan Ringan",
      "thunderstorm": "Badai Petir",
      "snow": "Salju"
    ],
    "folders": "Folder",
    "emptyFolder":
        "Folder ini kosong. Pindahkan percakapan ke sini dari menu obrolan.",
    "title": "Info & Sumber Daya",
    "noChats": "Tidak ada obrolan terbaru",
    "noServices": "Tidak ada area pengetahuan tersedia",
    "noServiceResults": "Tidak ditemukan area pengetahuan untuk \"{term}\"",
    "errorLoadingServices": "Gagal memuat area pengetahuan. Silakan coba lagi.",
    "relatedDocs": "Dokumen Terkait",
    "noDocuments": "Tidak ada dokumen terkait",
    "faq": "Pertanyaan yang Sering Diajukan",
    "tab": [
      "all": "Semua Obrolan",
      "folders": "Folder",
      "starred": "Berbintang",
      "archived": "Diarsipkan"
    ],
    "savedChats": "Obrolan Tersimpan",
    "chats": "Obrolan",
    "allChats": "Semua Obrolan",
    "noFolder": "Tanpa Folder",
    "starredChats": "Obrolan Berbintang",
    "archivedChats": "Obrolan Diarsipkan",
    "noStarredChats":
        "Belum ada percakapan berbintang. Beri bintang pada percakapan untuk menambahkannya di sini.",
    "noArchivedChats": "Belum ada percakapan yang diarsipkan.",
    "noSearchResults": "Tidak ditemukan percakapan untuk \"{term}\"",
    "loadingChats": "Memuat percakapan...",
    "errorLoadingConversations": "Gagal memuat percakapan. Silakan coba lagi.",
    "errorLoadingUser":
        "Data pengguna tidak lengkap. Silakan muat ulang halaman.",
    "errorNoUser": "Data pengguna hilang. Silakan muat ulang halaman.",
    "retry": "Coba Lagi",
    "message": "pesan",
    "messages": "pesan",
    "created": "Dibuat",
    "updated": "Diperbarui",
    "star": "Beri Bintang",
    "unstar": "Hapus Bintang",
    "archive": "Arsipkan",
    "unarchive": "Batalkan Arsip",
    "chatStarred": "Percakapan telah diberi bintang",
    "chatUnstarred": "Bintang pada percakapan telah dihapus",
    "chatArchived": "Percakapan telah diarsipkan",
    "chatUnarchived": "Percakapan telah dibatalkan pengarsipannya",
    "errorUpdatingChat": "Gagal memperbarui percakapan",
    "chatRenamed": "Percakapan berhasil diganti namanya",
    "errorRenamingChat": "Gagal mengganti nama percakapan",
    "chatDeleted": "Percakapan berhasil dihapus",
    "errorDeletingChat": "Gagal menghapus percakapan",
    "chatMoved": "Percakapan berhasil dipindahkan",
    "errorMovingChat": "Gagal memindahkan percakapan",
    "noPreview": "Pratinjau tidak tersedia",
    "searchConversations": "Cari percakapan...",
    "selectFolderInstruction": "Pilih folder untuk melihat percakapannya",
    "folderCreated": "Folder berhasil dibuat",
    "errorCreatingFolder": "Gagal membuat folder",
    "errorLoadingFolders": "Gagal memuat folder",
    "folderUpdated": "Folder berhasil diperbarui",
    "errorUpdatingFolder": "Gagal memperbarui folder",
    "folderDeleted": "Folder berhasil dihapus",
    "errorDeletingFolder": "Gagal menghapus folder",
    "chatRemovedFromFolders": "Percakapan dihapus dari folder",
    "errorRemovingChat": "Gagal menghapus percakapan dari folder",
    "id": "ID",
    "labels": "Label",
    "confidence": "Kepercayaan",
    "unknown": "Tidak Diketahui",
    "open": "Buka",
    "faqError": "FAQ tidak tersedia",
    "matchFound": "Kecocokan ditemukan",
    "noConversations": "Tidak ada percakapan ditemukan",
    "noStarred": "Tidak ada percakapan berbintang",
    "noArchived": "Tidak ada percakapan diarsipkan",
    "folderEmptyState": "Folder kosong"
  ],
  "leftPanel": [
    "cat1": [
      "name": "1. Identitas & Pencatatan Sipil",
      "children": [
        "Akta kelahiran",
        "Kartu Tanda Penduduk (KTP)",
        "Paspor",
        "Akta perkawinan dan kematian",
        "Pendaftaran pemilih"
      ]
    ],
    "cat2": [
      "name": "2. Layanan Kesehatan & Sosial",
      "children": [
        "Akses layanan kesehatan publik",
        "Program vaksinasi",
        "Asuransi kesehatan",
        "Tunjangan disabilitas",
        "Bantuan kesejahteraan dan pangan"
      ]
    ],
    "cat3": [
      "name": "3. Pendidikan & Pembelajaran",
      "children": [
        "Sekolah negeri dan universitas",
        "Beasiswa dan pinjaman pelajar",
        "Program pendidikan dewasa",
        "Sumber belajar daring"
      ]
    ],
    "cat4": [
      "name": "4. Ketenagakerjaan & Layanan Tenaga Kerja",
      "children": [
        "Pencarian kerja dan tunjangan pengangguran",
        "Perlindungan pekerja dan hak tenaga kerja",
        "Peraturan keselamatan kerja",
        "Pelatihan keterampilan dan magang"
      ]
    ],
    "cat5": [
      "name": "5. Pajak & Pendapatan",
      "children": [
        "Pelaporan dan pengembalian pajak penghasilan",
        "Pembayaran pajak properti",
        "Kepatuhan pajak bisnis",
        "Bea cukai dan bea masuk"
      ]
    ],
    "cat6": [
      "name": "6. Keselamatan Publik & Keadilan",
      "children": [
        "Polisi dan layanan darurat",
        "Layanan pengadilan dan bantuan hukum",
        "Pelaporan kejahatan",
        "Hukum perlindungan konsumen"
      ]
    ],
    "cat7": [
      "name": "7. Transportasi & Mobilitas",
      "children": [
        "Surat izin mengemudi dan pendaftaran kendaraan",
        "Transportasi umum dan infrastruktur",
        "Pelanggaran lalu lintas dan denda",
        "Program keselamatan jalan raya"
      ]
    ],
    "cat8": [
      "name": "8. Perumahan & Pembangunan Kota",
      "children": [
        "Bantuan perumahan rakyat",
        "Pendaftaran properti dan catatan tanah",
        "Pinjaman perumahan dan subsidi",
        "Zonasi dan izin bangunan"
      ]
    ],
    "cat9": [
      "name": "9. Utilitas & Lingkungan",
      "children": [
        "Layanan air dan listrik",
        "Pengelolaan limbah dan daur ulang",
        "Peraturan lingkungan",
        "Inisiatif energi terbarukan"
      ]
    ],
    "cat10": [
      "name": "10. Bisnis & Perdagangan",
      "children": [
        "Pendaftaran dan perizinan bisnis",
        "Peraturan perdagangan dan izin",
        "Hibah dan insentif usaha kecil",
        "E-commerce dan dukungan bisnis digital"
      ]
    ],
    "cat11": [
      "name": "11. Jaminan Sosial & Pensiun",
      "children": [
        "Manfaat pensiun",
        "Pengelolaan dana pensiun",
        "Manfaat bagi ahli waris",
        "Pensiun disabilitas"
      ]
    ],
    "cat12": [
      "name": "12. Komunitas & Keterlibatan Sipil",
      "children": [
        "Pemungutan suara dan pemilihan umum",
        "Umpan balik publik dan keluhan warga",
        "Sukarelawan dan program komunitas",
        "Partisipasi pemerintah daerah"
      ]
    ]
  ],
  "settings": [
    "title": "Pengaturan",
    "save": "Simpan",
    "close": "Tutup",
    "saveSettings": "Simpan Pengaturan",
    "savingSettings": "Menyimpan pengaturan Anda...",
    "settingsSaved": "Pengaturan berhasil disimpan!",
    "saveSuccess": "Pengaturan berhasil disimpan",
    "saveError": "Kesalahan saat menyimpan pengaturan",
    "display": "Tampilan",
    "displayLanguage": "Bahasa Tampilan",
    "languages": [
      "english": "Inggris",
      "french": "Prancis",
      "swahili": "Swahili"
    ],
    "theme": "Tema",
    "themes": ["light": "Terang", "dark": "Gelap", "system": "Sistem"],
    "themeLight": "Terang",
    "themeDark": "Gelap",
    "fontSize": "Ukuran Font",
    "notifications": "Notifikasi",
    "emailUpdates": "Pembaruan email",
    "soundNotifications": "Notifikasi suara",
    "accountManagement": "Manajemen Akun",
    "emailAddress": "Alamat Email",
    "emailAddressPlaceholder": "Alamat email Anda",
    "password": "Kata Sandi",
    "changePassword": "Ubah Kata Sandi",
    "resetUserData": "Setel Ulang Data Pengguna",
    "resetUserDataDesc":
        "Ini akan menghapus semua data profil dan riwayat obrolan Anda.",
    "deleteAccount": "Hapus Akun",
    "deleteAccountDesc":
        "Ini akan menghapus akun Anda dan semua data terkait secara permanen.",
    "edit": "Edit",
    "standardAccount": "Akun Standar",
    "confirmEmailChange": "Konfirmasi Perubahan Email",
    "pleaseEnterPassword": "Silakan masukkan kata sandi Anda",
    "cancel": "Batal",
    "account": [
      "title": "Akun",
      "resetDescription":
          "Ini akan menghapus semua data profil dan riwayat obrolan Anda.",
      "confirmReset":
          "Apakah Anda yakin ingin menyetel ulang semua data Anda? Ini tidak dapat dibatalkan.",
      "resetComplete": "Data Anda telah disetel ulang."
    ],
    "language": ["title": "Bahasa", "selectLabel": "Bahasa Tampilan"],
    "appearance": [
      "title": "Tampilan",
      "lightTheme": "Terang",
      "darkTheme": "Gelap",
      "systemTheme": "Sistem"
    ],
    "confirmDeleteAccount":
        "Apakah Anda yakin ingin menghapus akun Anda? Tindakan ini tidak dapat dibatalkan.",
    "confirmAccountDeletion": "Konfirmasi Penghapusan Akun",
    "accountDeletionWarning":
        "Peringatan: Tindakan ini bersifat permanen dan tidak dapat dibatalkan. Semua data Anda akan dihapus secara permanen.",
    "deletionReason": "Alasan penghapusan (opsional):",
    "deletionReasonPlaceholder":
        "Apa yang membuat Anda memutuskan untuk menghapus akun Anda?",
    "enterPasswordConfirm": "Masukkan kata sandi Anda untuk konfirmasi:",
    "currentPasswordPlaceholder": "Kata sandi Anda saat ini",
    "deleting": "Menghapus...",
    "permanentlyDeleteAccount": "Hapus Akun",
    "accountDeletedSuccess": "Akun Anda telah berhasil dihapus.",
    "incorrectPassword": "Kata sandi salah",
    "accountDeletionFailed": "Gagal menghapus akun. Silakan coba lagi nanti.",
    "confirmChange": "Konfirmasi Perubahan",
    "processing": "Memproses...",
    "userDataReset": "Data profil Anda telah berhasil disetel ulang.",
    "failedToResetUserData":
        "Gagal menyetel ulang data profil Anda. Silakan coba lagi nanti.",
    "changingEmailTo": "Mengubah email Anda menjadi",
    "will": "akan",
    "logOutSystem": "Mengeluarkan Anda dari sistem",
    "sendVerificationLink": "Mengirim tautan verifikasi ke email baru Anda",
    "requireVerification":
        "Memerlukan verifikasi sebelum Anda dapat masuk lagi",
    "checkNewEmailVerification":
        "Silakan periksa email baru Anda untuk instruksi verifikasi.",
    "unableToVerifyEmail":
        "Tidak dapat memverifikasi email. Silakan coba lagi.",
    "emailAlreadyInUse": "Email sudah digunakan",
    "enterValidEmail": "Harap masukkan alamat email yang valid",
    "failedToUpdateEmail": "Gagal memperbarui email. Silakan coba lagi.",
    "passwordResetInitiated":
        "Tautan setel ulang kata sandi telah dikirim ke alamat email Anda.",
    "unableToLoadUser":
        "Tidak dapat memuat informasi pengguna. Silakan coba lagi.",
    "retry": "Coba Lagi",
    "user": "Pengguna",
    "loadingUserInfo": "Memuat informasi pengguna...",
    "resetUserDataTitle": "Setel Ulang Data Pengguna",
    "confirmResetUserData":
        "Apakah Anda yakin ingin menyetel ulang semua data profil Anda? Ini akan menghapus semua informasi profil dan riwayat obrolan Anda, tetapi tetap menyimpan kredensial akun Anda.",
    "reset": "Setel Ulang",
    "deleteAccountTitle": "Hapus Akun"
  ],
  "userProfile": [
    "title": "Profil Pengguna",
    "privacyInfo":
        "Dengan memberikan lebih banyak informasi, Anda akan mendapatkan respons yang lebih akurat dan bermakna dari chatbot. Silakan tinjau kami",
    "privacyPolicyLink": "Kebijakan Privasi",
    "tabComingSoon":
        "Tab ini sedang dalam pengembangan dan akan segera tersedia.",
    "saveSuccess": "Profil berhasil disimpan",
    "loadError": "Kesalahan memuat data profil",
    "saveError": "Kesalahan menyimpan profil",
    "confirmSaveTitle": "Simpan Profil",
    "confirmSave": "Apakah Anda yakin ingin menyimpan perubahan ini?",
    "confirmCancel":
        "Anda memiliki perubahan yang belum disimpan. Apakah Anda yakin ingin membatalkan?",
    "confirmLeave":
        "Apakah Anda yakin ingin pergi? Perubahan yang belum disimpan akan hilang.",
    "confirmDiscardChanges": "Buang perubahan yang belum disimpan?",
    "uploadPhoto": "Unggah Foto",
    "uploadFile": "Unggah Berkas",
    "photoRequirements":
        "Foto harus jelas, terbaru, dan menampilkan wajah penuh Anda",
    "biometricRequirements": "Hanya berkas data biometrik resmi yang diterima",
    "documentUpload": "Unggah Dokumen",
    "validationTitle": "Harap perbaiki kesalahan berikut:",
    "profileIcon": "Ikon Profil",
    "change": "Ubah",
    "chooseProfileIcon": "Pilih Ikon Profil",
    "presetIcons": "Ikon Preset",
    "upload": "Unggah",
    "initials": "Inisial",
    "clickToUpload": "Klik untuk mengunggah",
    "useThisImage": "Gunakan Gambar Ini",
    "useInitials": "Gunakan Inisial",
    "tabs": [
      "tab1": "Data Identitas Pribadi",
      "tab2": "Pencatatan Sipil & Dokumentasi",
      "tab3": "Informasi Alamat & Tempat Tinggal",
      "tab4": "Dokumen Identitas & Perjalanan",
      "tab5": "Rekam Kesehatan & Medis",
      "tab6": "Data Ketenagakerjaan & Ekonomi",
      "tab7": "Pendidikan & Catatan Akademik",
      "tab8": "Data Keuangan & Pajak",
      "tab9": "Jaminan Sosial & Kesejahteraan",
      "tab10": "Catatan Pidana & Hukum",
      "tab11": "Transportasi & Mobilitas",
      "tab12": "Partisipasi Sipil & Politik"
    ],
    "tabsShort": [
      "personal": "Pribadi",
      "civil": "Sipil",
      "address": "Alamat",
      "identity": "Identitas",
      "health": "Kesehatan",
      "employment": "Pekerjaan",
      "education": "Pendidikan",
      "financial": "Keuangan",
      "social": "Sosial",
      "criminal": "Pidana",
      "transport": "Transportasi",
      "civic": "Sipil"
    ],
    "actions": [
      "cancel": "Batal",
      "save": "Simpan Profil",
      "previous": "Sebelumnya",
      "next": "Berikutnya",
      "saving": "Menyimpan..."
    ],
    "fields": [
      "fullName": "Nama lengkap (termasuk alias)",
      "dob": "Tanggal lahir",
      "gender": "Jenis Kelamin",
      "nationality": "Kewarganegaraan",
      "maritalStatus": "Status pernikahan",
      "photograph": "Foto",
      "biometric": "Sidik Jari / Data Biometrik",
      "birthCert": "Akta kelahiran",
      "deathCert": "Akta kematian",
      "marriageDivorce": "Catatan Pernikahan / Perceraian",
      "adoption": "Catatan adopsi",
      "citizenship": "Dokumen Kewarganegaraan / Naturalisasi",
      "immigration": "Riwayat imigrasi & visa",
      "currentAddress": "Alamat tempat tinggal saat ini",
      "previousAddresses": "Alamat sebelumnya",
      "postalCode": "Kode Pos",
      "country": "Negara",
      "residencyStatus": "Status Tempat Tinggal",
      "homeOrRental": "Detail kepemilikan rumah atau sewa",
      "utilityBills": "Tagihan utilitas yang terkait dengan alamat",
      "landRecords": "Catatan kepemilikan tanah dan properti",
      "idCard": "Nomor Kartu Tanda Penduduk",
      "passport": "Detail paspor",
      "driversLicense": "Surat Izin Mengemudi",
      "voterId": "ID Pemilih",
      "ssn": "Nomor Jaminan Sosial / Asuransi Nasional",
      "militaryRecords": "Catatan dinas militer",
      "medicalHistory": "Riwayat medis dan kondisi kesehatan",
      "vaccinations": "Catatan vaksinasi",
      "insuranceDetails": "Detail asuransi kesehatan",
      "disability": "Status disabilitas",
      "bloodType": "Golongan Darah",
      "organDonor": "Status donor organ",
      "prescriptions": "Resep dan perawatan yang diterima",
      "mentalHealth": "Riwayat kesehatan mental",
      "eHistory": "Riwayat pekerjaan",
      "currentEmployer": "Detail pemberi kerja saat ini",
      "workPermits": "Izin kerja dan kontrak kerja",
      "certifications": "Sertifikasi dan lisensi profesional",
      "unemployment": "Status pengangguran dan tunjangan yang diterima",
      "tin": "Nomor Pokok Wajib Pajak (NPWP)",
      "businessAffiliations": "Kepemilikan bisnis dan afiliasi perusahaan",
      "schools": "Sekolah dan universitas yang dihadiri",
      "education": "Pendidikan",
      "degrees": "Diploma, gelar, dan sertifikat",
      "performance": "Kinerja akademik dan skor tes",
      "academicRecords": "Catatan Akademik",
      "scholarships": "Beasiswa dan bantuan keuangan yang diterima",
      "incomeTax": "Catatan pajak penghasilan",
      "bankAccounts": "Rekunung bank dan keuangan",
      "propertyTax": "Pembayaran pajak properti",
      "businessTax": "Pelaporan pajak bisnis",
      "pensionContrib": "Iuran pensiun dan penarikan",
      "loanAid": "Catatan pinjaman dan bantuan pemerintah",
      "pensionStatus": "Status pensiun dan iuran",
      "childcare": "Dukungan penitipan anak",
      "foodAssistance": "Bantuan pangan / program kesejahteraan",
      "housingAssistance": "Bantuan perumahan",
      "policeRecords":
          "Catatan polisi (riwayat kriminal, penangkapan, tuduhan)",
      "courtCases": "Riwayat kasus pengadilan",
      "finesPenalties": "Denda dan hukuman",
      "paroleProbation": "Status pembebasan bersyarat atau masa percobaan",
      "citizenshipRevocation": "Pencabutan kewarganegaraan (jika berlaku)",
      "vehicleReg": "Detail pendaftaran kendaraan",
      "trafficViolations": "Pelanggaran lalu lintas dan denda",
      "licenseHistory": "Riwayat surat izin mengemudi dan pengesahan",
      "publicTransportCard": "Penggunaan kartu transportasi umum",
      "voterRegistration": "Detail pendaftaran pemilih",
      "electionHistory": "Riwayat partisipasi pemilu",
      "partyMembership": "Keanggotaan partai politik",
      "militaryStatus": "Status dinas militer atau wajib militer",
      "publicServiceRoles": "Peran layanan publik"
    ],
    "placeholders": [
      "fullName": "Masukkan nama lengkap resmi Anda",
      "nationality": "Masukkan kewarganegaraan Anda",
      "searchCountries": "Cari negara...",
      "selectCountry": "Pilih negara",
      "searchDisciplines": "Cari disiplin ilmu...",
      "selectDiscipline": "Pilih disiplin ilmu",
      "searchDegrees": "Cari gelar...",
      "selectDegree": "Pilih gelar"
    ],
    "validation": [
      "nameRequired": "Nama lengkap wajib diisi",
      "dobRequired": "Tanggal lahir wajib diisi",
      "dobFuture": "Tanggal lahir tidak boleh di masa depan",
      "requiredField": "{field} wajib diisi",
      "invalidFormat": "Format tidak valid untuk {field}",
      "futureDate": "Tanggal tidak boleh di masa depan",
      "invalidSelection": "Harap buat pilihan yang valid",
      "passwordLength": "Kata sandi harus terdiri dari minimal 8 karakter",
      "matchError": "Kolom tidak cocok"
    ],
    "errors": [
      "savingFailed": "Gagal menyimpan profil",
      "loadingFailed": "Gagal memuat data profil",
      "invalidForm": "Harap isi semua kolom yang wajib diisi",
      "invalidFileType": "Jenis berkas tidak valid",
      "fileTooLarge": "Berkas terlalu besar",
      "countryLoadError": "Kesalahan memuat negara",
      "countryUpdateError": "Kesalahan memperbarui negara"
    ],
    "notifications": [
      "saveSuccess": "Profil berhasil disimpan",
      "saveFailed": "Gagal menyimpan profil",
      "loadSuccess": "Profil berhasil dimuat",
      "loadFailed": "Gagal memuat profil",
      "fieldRequired": "Kolom ini wajib diisi",
      "uploadSuccess": "Berkas berhasil diunggah",
      "uploadFailed": "Gagal mengunggah berkas",
      "formChanged": "Anda memiliki perubahan yang belum disimpan",
      "sessionExpired": "Sesi Anda telah berakhir, silakan masuk lagi",
      "profileUpdated": "Profil Anda telah diperbarui",
      "profileIncomplete": "Profil Anda tidak lengkap"
    ],
    "instructions": [
      "fullNameHelp":
          "Masukkan nama lengkap resmi Anda seperti yang tertera pada dokumen resmi Anda",
      "dobHelp": "Masukkan tanggal lahir Anda dalam format BB/HH/TTTT",
      "uploadPhotoHelp":
          "Unggah foto terbaru. Berkas harus berupa JPG, PNG, atau GIF dan kurang dari 2MB",
      "passwordHelp":
          "Kata sandi harus terdiri dari minimal 8 karakter dengan satu huruf besar, satu angka, dan satu karakter khusus",
      "documentHelp": "Format yang diterima: PDF, JPG, PNG (maks 5MB)",
      "requiredFields": "Kolom yang ditandai dengan * wajib diisi",
      "selectFromList": "Silakan pilih opsi dari daftar",
      "nextTab": "Lanjutkan ke bagian berikutnya",
      "previousTab": "Kembali ke bagian sebelumnya",
      "saveInstructions": "Klik Simpan untuk menyimpan informasi Anda",
      "cancelInstructions": "Klik Batal untuk membuang perubahan"
    ],
    "completionStatus": [
      "notStarted": "Belum Dimulai",
      "inProgress": "Sedang Berlangsung",
      "complete": "Selesai",
      "percentComplete": "{percent}% selesai",
      "tabsCompleted": "{completed} dari {total} bagian selesai",
      "tabComplete": "Tab selesai!"
    ],
    "gender": [
      "male": "Pria",
      "female": "Wanita",
      "other": "Lainnya",
      "preferNot": "Pilih untuk tidak mengatakan"
    ],
    "maritalStatus": [
      "single": "Lajang",
      "married": "Menikah",
      "divorced": "Cerai",
      "widowed": "Janda/Duda",
      "other": "Lainnya"
    ],
    "residencyStatuses": [
      "citizen": "Warga Negara",
      "permanentResident": "Penduduk Tetap",
      "temporaryResident": "Penduduk Sementara",
      "other": "Lainnya"
    ],
    "employmentStatuses": [
      "employed": "Bekerja",
      "selfEmployed": "Wiraswasta",
      "unemployed": "Menganggur",
      "student": "Pelajar",
      "retired": "Pensiunan",
      "homemaker": "Ibu/Bapak Rumah Tangga",
      "other": "Lainnya"
    ],
    "educationLevels": [
      "primary": "Pendidikan Dasar",
      "secondary": "Pendidikan Menengah",
      "highSchool": "Sekolah Menengah Atas",
      "vocational": "Pelatihan Kejuruan",
      "associate": "Gelar Associate",
      "bachelor": "Gelar Sarjana",
      "master": "Gelar Magister",
      "doctoral": "Gelar Doktor",
      "professional": "Gelar Profesional",
      "other": "Lainnya"
    ],
    "proficiencyLevels": [
      "native": "Penutur Asli",
      "fluent": "Fasih",
      "advanced": "Mahir",
      "intermediate": "Menengah",
      "basic": "Dasar"
    ],
    "bloodTypes": [
      "aPositive": "A+",
      "aNegative": "A-",
      "bPositive": "B+",
      "bNegative": "B-",
      "abPositive": "AB+",
      "abNegative": "AB-",
      "oPositive": "O+",
      "oNegative": "O-",
      "unknown": "Tidak Diketahui"
    ],
    "languages": [
      "english": "Inggris",
      "french": "Prancis",
      "swahili": "Swahili",
      "arabic": "Arab",
      "spanish": "Spanyol",
      "portuguese": "Portugis",
      "chinese": "Mandarin",
      "japanese": "Jepang",
      "german": "Jerman",
      "russian": "Rusia",
      "hindi": "Hindi",
      "urdu": "Urdu",
      "other": "Lainnya"
    ],
    "yesNo": ["yes": "Ya", "no": "Tidak"],
    "select": "Silakan pilih",
    "existingFile": "Berkas yang ada",
    "noMatchingCountries": "Tidak ada negara yang cocok ditemukan",
    "noMatchingDisciplines": "Tidak ada disiplin ilmu yang cocok ditemukan",
    "noMatchingDegrees": "Tidak ada gelar yang cocok ditemukan",
    "educationOptions": [
      "Akuntansi",
      "Teknik Dirgantara",
      "Ilmu Pertanian",
      "Antropologi",
      "Arsitektur",
      "Sejarah Seni",
      "Kecerdasan Buatan",
      "Astronomi",
      "Astrofisika",
      "Biokimia",
      "Teknik Biomedis",
      "Bioteknologi",
      "Administrasi Bisnis",
      "Teknik Kimia",
      "Kimia",
      "Teknik Sipil",
      "Komunikasi",
      "Teknik Komputer",
      "Ilmu Komputer",
      "Manajemen Konstruksi",
      "Peradilan Pidana",
      "Keamanan Siber",
      "Ilmu Data",
      "Kedokteran Gigi",
      "Ekonomi",
      "Pendidikan",
      "Teknik Elektro",
      "Pendidikan Dasar",
      "Sastra Inggris",
      "Teknik Lingkungan",
      "Ilmu Lingkungan",
      "Desain Mode",
      "Studi Film",
      "Keuangan",
      "Seni Rupa",
      "Ilmu Pangan",
      "Ilmu Forensik",
      "Desain Game",
      "Geografi",
      "Geologi",
      "Desain Grafis",
      "Administrasi Kesehatan",
      "Sejarah",
      "Manajemen Perhotelan",
      "Sumber Daya Manusia",
      "Desain Industri",
      "Teknik Industri",
      "Sistem Informasi",
      "Teknologi Informasi",
      "Desain Interior",
      "Bisnis Internasional",
      "Hubungan Internasional",
      "Jurnalisme",
      "Hukum",
      "Ilmu Perpustakaan",
      "Linguistik",
      "Manajemen",
      "Pemasaran",
      "Ilmu Material",
      "Matematika",
      "Teknik Mesin",
      "Studi Media",
      "Kedokteran",
      "Meteorologi",
      "Mikrobiologi",
      "Musik",
      "Nanoteknologi",
      "Keperawatan",
      "Nutrisi",
      "Terapi Okupasi",
      "Oseanografi",
      "Teknik Perminyakan",
      "Farmasi",
      "Filsafat",
      "Fotografi",
      "Pendidikan Jasmani",
      "Terapi Fisik",
      "Fisika",
      "Ilmu Politik",
      "Psikologi",
      "Administrasi Publik",
      "Kesehatan Masyarakat",
      "Hubungan Masyarakat",
      "Robotika",
      "Pendidikan Menengah",
      "Pekerjaan Sosial",
      "Sosiologi",
      "Rekayasa Perangkat Lunak",
      "Pendidikan Luar Biasa",
      "Manajemen Olahraga",
      "Statistik",
      "Teknik Sistem",
      "Seni Teater",
      "Pariwisata",
      "Perencanaan Kota",
      "Kedokteran Hewan",
      "Pengembangan Web",
      "Biologi Satwa Liar",
      "Zoologi"
    ],
    "degreeOptions": [
      "Gelar Associate",
      "Sarjana Seni (BA)",
      "Sarjana Sains (BS)",
      "Sarjana Teknik (BEng)",
      "Sarjana Administrasi Bisnis (BBA)",
      "Sarjana Seni Rupa (BFA)",
      "Sarjana Pendidikan (BEd)",
      "Sarjana Kedokteran (MBBS)",
      "Sarjana Hukum (LLB)",
      "Magister Seni (MA)",
      "Magister Sains (MS)",
      "Magister Administrasi Bisnis (MBA)",
      "Magister Teknik (MEng)",
      "Magister Seni Rupa (MFA)",
      "Magister Pendidikan (MEd)",
      "Magister Hukum (LLM)",
      "Magister Kesehatan Masyarakat (MPH)",
      "Doktor Filsafat (PhD)",
      "Doktor Kedokteran (MD)",
      "Doktor Pendidikan (EdD)",
      "Doktor Administrasi Bisnis (DBA)",
      "Doktor Yurisprudensi (JD)",
      "Diploma Profesional",
      "Diploma Teknis",
      "Sertifikat Kejuruan",
      "Sertifikat Pascasarjana",
      "Diploma Pascasarjana",
      "Pasca Doktoral"
    ],
    "aria": [
      "tabList": "Bagian formulir profil",
      "nextButton": "Buka bagian berikutnya",
      "prevButton": "Buka bagian sebelumnya",
      "closeButton": "Tutup formulir profil",
      "saveButton": "Simpan data profil",
      "requiredField": "Kolom wajib diisi",
      "dropdownSelect": "Pilih opsi"
    ]
  ],
  "chatbot": [
    "placeholder": "Ketik pertanyaan Anda di sini...",
    "sendButton": "Kirim",
    "fileReceived": "Berkas berhasil diterima.",
    "fileUploadError": "Kesalahan mengunggah berkas.",
    "processingError": "Kesalahan memproses permintaan Anda.",
    "welcomeMessage":
        "Selamat datang! Bagaimana saya dapat membantu Anda dengan layanan pemerintah Kenya hari ini?",
    "attachFile": "Lampirkan Berkas",
    "fileTooLarge": "Berkas terlalu besar. Ukuran maksimum adalah {maxSize}.",
    "saveChat": "Simpan Obrolan",
    "chatSaved": "Obrolan Disimpan",
    "chatTitle": "Judul Obrolan",
    "chatTitlePlaceholder": "Masukkan judul untuk obrolan ini",
    "selectFolder": "Pilih Folder",
    "newChat": "Obrolan Baru",
    "clearContext": "Hapus konteks dan mulai percakapan baru",
    "unsavedChanges":
        "Anda memiliki perubahan yang belum disimpan. Apakah Anda yakin ingin memulai obrolan baru?",
    "whatCanIHelp": "Bagaimana saya bisa membantu Anda hari ini?",
    "justChat": "Hanya Mengobrol",
    "queryContext": "Konteks Kueri",
    "contextAdded": "Konteks ditambahkan ke kueri Anda",
    "contextRemoved": "Konteks dihapus dari kueri Anda",
    "sessionUpdated": "Sesi diperbarui",
    "newChatStarted": "Memulai percakapan baru",
    "loadError": "Tidak dapat memuat riwayat obrolan",
    "responsePrefix": "Saya menerima pesan Anda",
    "withContext": "dengan konteks",
    "conversationLoaded": "Percakapan berhasil dimuat!",
    "saveConfirmTitle": "Simpan Percakapan yang Ada",
    "saveConfirmMessage": "Simpan percakapan yang ada?",
    "loadConfirmTitle": "Muat Percakapan yang Ada",
    "loadConfirmMessage":
        "Anda memiliki perubahan yang belum disimpan. Apakah Anda ingin membuangnya dan memuat percakapan yang dipilih, atau menyimpan percakapan saat ini terlebih dahulu?",
    "loadAndDiscard": "Muat dan Buang",
    "saveAndLoad": "Simpan dan Muat",
    "saveAndStartNew": "Simpan dan Mulai Baru",
    "discardAndStartNew": "Buang dan Mulai Baru",
    "newChatTitle": "Mulai Obrolan Baru",
    "exportChat": "Ekspor Obrolan",
    "exportFilename": "Nama Berkas",
    "exportFilenamePlaceholder": "Masukkan nama berkas",
    "exportButton": "Ekspor",
    "exportSuccess": "Obrolan berhasil diekspor",
    "exportError": "Gagal mengekspor obrolan. Silakan coba lagi.",
    "thinking": "Genie sedang berpikir...",
    "contextPrefix": "Konteks:",
    "removeContext": "Hapus Konteks",
    "dialogs": [
      "newChatTitle": "Mulai Obrolan Baru?",
      "newChatContent":
          "Anda memiliki perubahan yang belum disimpan. Tetap mulai obrolan baru?",
      "loadChatTitle": "Muat Percakapan?",
      "loadChatContent":
          "Anda memiliki perubahan yang belum disimpan. Tetap muat?",
      "saveTitle": "Simpan Percakapan",
      "saveHint": "Masukkan judul percakapan",
      "exportTitle": "Ekspor Obrolan ke PDF",
      "exportHint": "Nama berkas (tanpa .pdf)",
      "actions": [
        "discardAndNew": "Buang & Baru",
        "discardAndLoad": "Buang & Muat",
        "saveFirst": "Simpan Dulu",
        "export": "Ekspor"
      ]
    ],
    "shareWhatsApp": "Bagikan di WhatsApp"
  ],
  "quickhelp": [
    "applyForID": "Ajukan KTP",
    "payTaxes": "Bayar Pajak",
    "startBusiness": "Mulai Bisnis",
    "findHealthcare": "Layanan Kesehatan",
    "educationServices": "Pendidikan",
    "transportLicenses": "Transportasi",
    "housingPrograms": "Perumahan",
    "findJobs": "Cari Kerja",
    "justChat": "Obrolan Santai",
    "applyForIDPrompt":
        "Bertindaklah sebagai ahli pendaftaran sipil Kenya yang membantu. Jelaskan langkah-langkah untuk mendapatkan KTP Nasional (Maisha Namba) atau mengganti yang hilang. PENTING: Berikan daftar dokumen yang diperlukan dengan jelas (misalnya, Akta Kelahiran, salinan KTP orang tua) dan sarankan pengguna untuk mengunjungi Huduma Centre atau kantor Pencatatan Sipil terdekat. ATURAN: Selalu sebut aplikasi sebagai 'Genie AI'.",
    "payTaxesPrompt":
        "Bertindaklah sebagai panduan KRA (Otoritas Pendapatan Kenya). Jelaskan proses pengajuan SPT, pengajuan PIN KRA, atau pengaturan ulang kata sandi di portal iTax. PENTING: Ingatkan pengguna tentang batas waktu 30 Juni untuk SPT tahunan dan pandu mereka tentang cara mengajukan SPT Nihil (Nil returns) jika mereka tidak memiliki penghasilan. ATURAN: Selalu sebut aplikasi sebagai 'Genie AI'.",
    "startBusinessPrompt":
        "Bertindaklah sebagai konsultan bisnis untuk layanan eCitizen. Pandu pengguna melalui pemesanan nama bisnis dan pendaftaran perusahaan di Kenya. PENTING: Jelaskan biaya saat ini untuk pencarian nama dan pendaftaran, dan arahkan pengguna ke portal resmi eCitizen untuk menyelesaikan aplikasi. ATURAN: Selalu sebut aplikasi sebagai 'Genie AI'.",
    "findHealthcarePrompt":
        "Bertindaklah sebagai navigator layanan kesehatan. Berikan informasi tentang transisi dari NHIF ke SHIF (Dana Asuransi Kesehatan Sosial) dan cara mendaftar. PENTING: Bagikan kode USSD resmi (seperti *263#) atau tautan situs web untuk pendaftaran dan jelaskan manfaat jaminan kesehatan masyarakat. ATURAN: Selalu sebut aplikasi sebagai 'Genie AI'.",
    "educationServicesPrompt":
        "Bertindaklah sebagai konselor pendidikan. Diskusikan kurikulum CBC, pendaftaran NEMIS, atau penempatan universitas melalui KUCCPS. PENTING: Jelaskan bagaimana orang tua dapat memeriksa hasil ujian nasional melalui SMS atau portal KNEC saat dirilis. ATURAN: Selalu sebut aplikasi sebagai 'Genie AI'.",
    "transportLicensesPrompt":
        "Bertindaklah sebagai panduan layanan NTSA. Jelaskan proses perpanjangan SIM, pemeriksaan kendaraan, atau pengelolaan akun TIMS. PENTING: Pandu pengguna tentang cara masuk ke portal eCitizen NTSA untuk mengajukan Smart DL atau memesan pemeriksaan kendaraan. ATURAN: Selalu sebut aplikasi sebagai 'Genie AI'.",
    "housingProgramsPrompt":
        "Bertindaklah sebagai penasihat program perumahan. Jelaskan pendaftaran Program Perumahan Terjangkau (Boma Yangu) dan proses kontribusi sukarela. PENTING: Pandu pengguna ke portal Boma Yangu untuk melihat proyek dan jelaskan kriteria kelayakan untuk alokasi. ATURAN: Selalu sebut aplikasi sebagai 'Genie AI'.",
    "findJobsPrompt":
        "Bertindaklah sebagai pelatih karir untuk layanan publik. Pandu pengguna membuat profil dan melamar lowongan melalui portal Komisi Layanan Publik (PSC). PENTING: Sarankan pengguna untuk menyiapkan sertifikat akademik mereka dan secara teratur memeriksa situs web PSC atau harian lokal untuk iklan MyGov. ATURAN: Selalu sebut aplikasi sebagai 'Genie AI'.",
    "justChatPrompt":
        "Bertindaklah sebagai teman lokal yang ramah. Bersikap sopan, membantu, dan berpengetahuan tentang budaya Kenya dan kehidupan sehari-hari. PENTING: Ingatkan pengguna bahwa meskipun Anda dapat mengobrol tentang apa saja, kekuatan utama Anda adalah membantu mereka menavigasi layanan pemerintah Kenya seperti **KTP**, **Pajak**, dan **Pendaftaran Bisnis**. ATURAN: Selalu sebut aplikasi sebagai 'Genie AI'.",
    "applyForIDUserPrompt":
        "Saya ingin mencari tahu tentang cara mengajukan kartu KTP Nasional di Kenya.",
    "payTaxesUserPrompt":
        "Saya ingin bertanya tentang membayar pajak atau mengajukan SPT KRA saya di Kenya.",
    "startBusinessUserPrompt":
        "Saya ingin mencari tahu tentang mendaftarkan bisnis atau perusahaan baru di Kenya.",
    "findHealthcareUserPrompt":
        "Saya ingin bertanya tentang fasilitas kesehatan masyarakat dan asuransi (NHIF/SHIF) di Kenya.",
    "educationServicesUserPrompt":
        "Saya ingin mencari tahu tentang sekolah dan layanan pendidikan di Kenya.",
    "transportLicensesUserPrompt":
        "Saya ingin bertanya tentang SIM dan layanan NTSA di Kenya.",
    "housingProgramsUserPrompt":
        "Saya ingin mencari tahu tentang Program Perumahan Terjangkau (Boma Yangu) di Kenya.",
    "findJobsUserPrompt":
        "Saya ingin bertanya tentang peluang kerja pemerintah dan lamaran PSC di Kenya.",
    "justChatUserPrompt":
        "Saya ingin mengobrol secara umum tentang kehidupan di Kenya."
  ],
  "common": [
    "cancel": "Batal",
    "create": "Buat",
    "save": "Simpan",
    "move": "Pindahkan",
    "delete": "Hapus",
    "ok": "OKE",
    "ingest": "Telan",
    "retract": "Tarik Kembali",
    "loading": "Memuat...",
    "refresh": "Segarkan",
    "open": "Buka",
    "done": "Selesai",
    "confirm": "Konfirmasi",
    "edit": "Edit"
  ],
  "feedback": [
    "title": "Umpan Balik",
    "button": "Umpan Balik",
    "positive": "Umpan balik positif",
    "negative": "Umpan balik negatif",
    "promptText": "Apakah respons ini membantu?",
    "placeholder": "Komentar tambahan...",
    "submit": "Kirim Umpan Balik",
    "close": "Batal",
    "thankYouMessage": "Terima kasih atas umpan balik Anda!",
    "submitting": "Mengirim...",
    "error": "Terjadi kesalahan. Silakan coba lagi.",
    "success": "Terima kasih atas umpan balik Anda!"
  ],
  "responseRating": [
    "title": "Bantu Kami Meningkatkan",
    "note":
        "Umpan balik Anda akan digunakan untuk menyetel chatbot dengan lebih baik dan meningkatkan respons dari waktu ke waktu.",
    "chatbotResponse": "Respons Chatbot:",
    "ratingLabels": [
      "1": "Tidak Berguna",
      "2": "Sedikit Membantu",
      "3": "Cukup Membantu",
      "4": "Sangat Membantu",
      "5": "Mengubah Hidup"
    ],
    "additionalComments": "Komentar tambahan...",
    "submit": "Kirim",
    "cancel": "Batal"
  ],
  "upload": ["alt": "Unggah"],
  "uploadDialog": [
    "title": "Unggah Berkas",
    "dropzone": "Seret & lepas berkas di sini, atau klik untuk memilih",
    "allowedTypesLabel": "Jenis yang diizinkan:",
    "buttonUpload": "Unggah {count} Berkas",
    "remove": "Hapus",
    "uploading": "Mengunggah...",
    "notifications": [
      "dropError":
          "Hanya berkas yang dapat dilepas. Harap periksa apakah Anda menyeret berkas yang valid dari komputer Anda.",
      "typeNotAllowed": "Jenis berkas \"{extension}\" tidak diizinkan.",
      "shortcutUnsupported":
          "Berkas pintasan (.url) tidak didukung. Harap seret berkas yang sebenarnya.",
      "duplicate": "Berkas \"{fileName}\" sudah ditambahkan.",
      "uploadSuccess": "Berhasil mengunggah {fileName}",
      "uploadFailed": "Gagal mengunggah {fileName}."
    ]
  ],
  "about": [
    "title": "Tentang",
    "version": "Versi",
    "description":
        "Genie AI adalah asisten cerdas Anda untuk menavigasi layanan dan informasi pemerintah.",
    "techStack": "Tech Stack",
    "copyright": "Hak cipta dilindungi undang-undang."
  ]
    ]
}
