"""
Potato crop thresholds.
Auto-generated by build_crop_profiles_pipeline.py — do not edit manually.
Source: data/example_crop_profile.json (derived from BAMIS crop calendars).
"""
from __future__ import annotations

import json
import os
from dataclasses import dataclass

_PROFILE_PATH = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "..", "..", "data", "example_crop_profile.json")
)

AVAILABLE_REGIONS: list[str] = ['dhaka']


@dataclass(frozen=True)
class PotatoThresholds:
    region: str
    temp_min: float
    temp_max: float
    humidity_min: float
    humidity_max: float
    rain_medium: float    # mm — "medium" severity threshold
    rain_critical: float  # mm — "critical" severity threshold
    wind_max: float


def load_potato_thresholds(
    region: str = "dhaka",
    path: str = _PROFILE_PATH,
) -> PotatoThresholds:
    """Load Potato thresholds for *region* from the crop profile JSON."""
    with open(path, encoding="utf-8") as f:
        profiles = json.load(f)

    key = f"potato_{region}"
    if key not in profiles:
        candidates = [k for k in profiles if k.startswith("potato_")]
        if not candidates:
            raise KeyError(f"No Potato profile found in {path!r}")
        key = candidates[0]
        region = key.split("_", 1)[1]

    raw = profiles[key]["crop_rules"]
    rain_rules = raw.get("rainfall_daily", [])
    rain_medium   = next((r["min"] for r in rain_rules if r.get("severity") == "medium"),   25.0)
    rain_critical = next((r["min"] for r in rain_rules if r.get("severity") == "critical"), 100.0)

    return PotatoThresholds(
        region=region,
        temp_min=float(raw.get("temperature_min", {}).get("min", 10.0)),
        temp_max=float(raw.get("temperature_max", {}).get("max", 35.0)),
        humidity_min=float(raw.get("humidity", {}).get("min", 60.0)),
        humidity_max=float(raw.get("humidity", {}).get("max", 90.0)),
        rain_medium=float(rain_medium),
        rain_critical=float(rain_critical),
        wind_max=float(raw.get("wind_speed_kmh", {}).get("max", 30.0)),
    )
