import os

# ArangoDB Connection
ARANGO_URL = os.getenv("ARANGO_URL", "http://arango-vector-db:8529")
ARANGO_USERNAME = os.getenv("ARANGO_USERNAME", "root")
ARANGO_PASSWORD = os.getenv("ARANGO_PASSWORD", "test")
ARANGO_DB_NAME = os.getenv("ARANGO_DB_NAME", "genie-ai")

# Collection/Graph settings
ARANGO_GRAPH_NAME = os.getenv("RETRIEVER_ARANGO_GRAPH_NAME", "GRAPH_TEST")

# Search settings — ARANGO_USE_APPROX_SEARCH permanently False (broken in this ArangoDB version)
ARANGO_USE_APPROX_SEARCH = False
ARANGO_DISTANCE_STRATEGY = os.getenv("RETRIEVER_ARANGO_DISTANCE_STRATEGY", "COSINE")
ARANGO_SEARCH_START = os.getenv("RETRIEVER_ARANGO_SEARCH_START", "chunk")
ARANGO_SEARCH_MODE = os.getenv("RETRIEVER_ARANGO_SEARCH_MODE", "vector")
ARANGO_NUM_CENTROIDS = int(os.getenv("RETRIEVER_ARANGO_NUM_CENTROIDS", 1))
ARANGO_FILTER_STRATEGY = os.getenv("RETRIEVER_ARANGO_FILTER_STRATEGY", "post_filter")

# Traversal settings
ARANGO_TRAVERSAL_ENABLED = os.getenv("RETRIEVER_ARANGO_TRAVERSAL_ENABLED", "false").lower() == "true"
ARANGO_TRAVERSAL_MAX_DEPTH = int(os.getenv("RETRIEVER_ARANGO_TRAVERSAL_MAX_DEPTH", 3))
ARANGO_TRAVERSAL_MAX_RETURNED = int(os.getenv("RETRIEVER_ARANGO_TRAVERSAL_MAX_RETURNED", 3))
ARANGO_TRAVERSAL_SCORE_THRESHOLD = float(os.getenv("RETRIEVER_ARANGO_TRAVERSAL_SCORE_THRESHOLD", 0.5))
ARANGO_TRAVERSAL_CONCURRENT_BATCHES = int(os.getenv("RETRIEVER_ARANGO_TRAVERSAL_CONCURRENT_BATCHES", 1))
ARANGO_TRAVERSAL_QUERY = os.getenv("RETRIEVER_ARANGO_TRAVERSAL_QUERY", "")

# TEI Embedding
TEI_EMBEDDING_ENDPOINT = os.getenv("TEI_EMBEDDING_ENDPOINT", "http://tei:80")
TEI_EMBED_MODEL = os.getenv("TEI_EMBED_MODEL", "")

# OpenAI settings
OPENAI_EMBED_ENABLED = False
OPENAI_EMBED_MODEL = os.getenv("RETRIEVER_OPENAI_EMBED_MODEL", "text-embedding-3-small")
OPENAI_CHAT_ENABLED = os.getenv("RETRIEVER_OPENAI_CHAT_ENABLED", "false").lower() == "true"
OPENAI_CHAT_MODEL = os.getenv("RETRIEVER_OPENAI_CHAT_MODEL", "gpt-4o")
OPENAI_CHAT_MAX_TOKENS = int(os.getenv("RETRIEVER_OPENAI_CHAT_MAX_TOKENS", 1024))
OPENAI_CHAT_TEMPERATURE = float(os.getenv("RETRIEVER_OPENAI_CHAT_TEMPERATURE", 0.7))
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")

# Summarizer
SUMMARIZER_ENABLED = os.getenv("RETRIEVER_SUMMARIZER_ENABLED", "false").lower() == "true"

# vLLM settings
VLLM_ENDPOINT = os.getenv("VLLM_ENDPOINT", "")
VLLM_MODEL_ID = os.getenv("VLLM_MODEL_ID", "")
VLLM_API_KEY = os.getenv("VLLM_API_KEY", "")
VLLM_MAX_NEW_TOKENS = int(os.getenv("VLLM_MAX_NEW_TOKENS", 1024))
VLLM_TEMPERATURE = float(os.getenv("VLLM_TEMPERATURE", 0.7))
VLLM_TOP_P = float(os.getenv("VLLM_TOP_P", 0.95))
VLLM_TIMEOUT = int(os.getenv("VLLM_TIMEOUT", 300))

# HuggingFace
HF_TOKEN = os.getenv("HF_TOKEN", "")
