# GENIE.AI Docker Swarm - El Salvador environment
# Same server as itu_rtx_test but separate stack

[itu_rtx_el_salvador]
genieai-sv ansible_host=10.0.0.110

[swarm_managers]
genieai-sv

[gpu_nodes]
genieai-sv

[all:vars]
ansible_user=govstack
