"""
generate_crop_modules.py
========================
Step 3 of build_crop_profiles_pipeline.py.

Reads example_crop_profile.json and emits, for every unique crop:

    app/crops/<crop>/
        __init__.py
        profile.py      — <CropName>Thresholds dataclass + loader
        risk_engine.py  — threshold evaluator + disease detectors

Disease detection functions are generated from the disease_risks[].when
conditions in the profile.  Diseases marked evaluable_with_current_feeds=false
are documented as comments but not turned into active checks.

Usage (standalone)
──────────────────
  python scripts/generate_crop_modules.py
  python scripts/generate_crop_modules.py --crop tomato
  python scripts/generate_crop_modules.py --profile /custom/path.json
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from textwrap import dedent
from typing import Any

_SCRIPTS_DIR  = Path(__file__).resolve().parent
_ENGINE_ROOT  = _SCRIPTS_DIR.parent
_DEFAULT_PROFILE = _ENGINE_ROOT / "data" / "example_crop_profile.json"
_DEFAULT_CROPS_DIR = _ENGINE_ROOT / "app" / "crops"

# ---------------------------------------------------------------------------
# Name helpers
# ---------------------------------------------------------------------------

def _to_class_name(crop: str) -> str:
    """'rice_aman' → 'RiceAman'"""
    return "".join(word.capitalize() for word in crop.split("_"))


def _to_display_name(crop: str) -> str:
    """'rice_aman' → 'Rice Aman'"""
    return " ".join(word.capitalize() for word in crop.split("_"))


def _to_func_slug(name: str) -> str:
    """'late_blight' → 'late_blight';  'Bacterial Wilt' → 'bacterial_wilt'"""
    slug = re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")
    return slug


# ---------------------------------------------------------------------------
# Disease condition → Python expression
# ---------------------------------------------------------------------------

# Maps 'when' key → (python_expr, optional_preamble_line)
_VAR_MAP: dict[str, tuple[str, str | None]] = {
    "temperature_mean":  ("temp_mean",       "    temp_mean = (day.temp_min + day.temp_max) / 2.0"),
    "temperature_min":   ("day.temp_min",     None),
    "temperature_max":   ("day.temp_max",     None),
    "humidity":          ("day.humidity_max", None),
    "precipitation":     ("day.rain_mm",      None),
    "rainfall_mm":       ("day.rain_mm",      None),
}


def _build_condition(var_key: str, bounds: dict[str, float], expr: str) -> str:
    mn = bounds.get("min")
    mx = bounds.get("max")
    if mn is not None and mx is not None:
        return f"({mn} <= {expr} <= {mx})"
    if mn is not None:
        return f"({expr} >= {mn})"
    if mx is not None:
        return f"({expr} <= {mx})"
    return "True"


def _render_disease_func(name: str, when: dict[str, Any]) -> str | None:
    """
    Return the Python source for one detect_<name>() function,
    or None if no supported weather variables are present in 'when'.
    """
    preambles: list[str] = []
    conditions: list[str] = []

    for var_key, bounds in when.items():
        if var_key not in _VAR_MAP:
            continue
        expr, preamble = _VAR_MAP[var_key]
        if preamble and preamble not in preambles:
            preambles.append(preamble)
        conditions.append(_build_condition(var_key, bounds, expr))

    if not conditions:
        return None

    slug = _to_func_slug(name)
    display = name.replace("_", " ").title()
    # Human-readable condition summary for the return string
    cond_summary = ", ".join(
        f"{k.replace('_', ' ')} {list(v.items())}"
        for k, v in when.items()
        if k in _VAR_MAP
    )

    body_lines: list[str] = []
    body_lines.append(f"def detect_{slug}(day: DailyForecastPoint) -> str | None:")
    if preambles:
        for p in preambles:
            body_lines.append(p)
    cond_expr = " and ".join(conditions)
    body_lines.append(f"    if {cond_expr}:")
    body_lines.append(f'        return "{display} risk: weather conditions match threshold"')
    body_lines.append("    return None")

    return "\n".join(body_lines)


# ---------------------------------------------------------------------------
# profile.py template
# ---------------------------------------------------------------------------

def _render_profile_py(
    crop: str,
    class_name: str,
    display_name: str,
    available_regions: list[str],
    default_region: str,
) -> str:
    regions_repr = repr(sorted(available_regions))
    return dedent(f'''\
        """
        {display_name} crop thresholds.
        Auto-generated by build_crop_profiles_pipeline.py — do not edit manually.
        Source: data/example_crop_profile.json (derived from BAMIS crop calendars).
        """
        from __future__ import annotations

        import json
        import os
        from dataclasses import dataclass

        _PROFILE_PATH = os.path.abspath(
            os.path.join(os.path.dirname(__file__), "..", "..", "..", "data", "example_crop_profile.json")
        )

        AVAILABLE_REGIONS: list[str] = {regions_repr}


        @dataclass(frozen=True)
        class {class_name}Thresholds:
            region: str
            temp_min: float
            temp_max: float
            humidity_min: float
            humidity_max: float
            rain_medium: float    # mm — "medium" severity threshold
            rain_critical: float  # mm — "critical" severity threshold
            wind_max: float


        def load_{crop}_thresholds(
            region: str = "{default_region}",
            path: str = _PROFILE_PATH,
        ) -> {class_name}Thresholds:
            """Load {display_name} thresholds for *region* from the crop profile JSON."""
            with open(path, encoding="utf-8") as f:
                profiles = json.load(f)

            key = f"{crop}_{{region}}"
            if key not in profiles:
                candidates = [k for k in profiles if k.startswith("{crop}_")]
                if not candidates:
                    raise KeyError(f"No {display_name} profile found in {{path!r}}")
                key = candidates[0]
                region = key.split("_", 1)[1]

            raw = profiles[key]["crop_rules"]
            rain_rules = raw.get("rainfall_daily", [])
            rain_medium   = next((r["min"] for r in rain_rules if r.get("severity") == "medium"),   25.0)
            rain_critical = next((r["min"] for r in rain_rules if r.get("severity") == "critical"), 100.0)

            return {class_name}Thresholds(
                region=region,
                temp_min=float(raw.get("temperature_min", {{}}).get("min", 10.0)),
                temp_max=float(raw.get("temperature_max", {{}}).get("max", 35.0)),
                humidity_min=float(raw.get("humidity", {{}}).get("min", 60.0)),
                humidity_max=float(raw.get("humidity", {{}}).get("max", 90.0)),
                rain_medium=float(rain_medium),
                rain_critical=float(rain_critical),
                wind_max=float(raw.get("wind_speed_kmh", {{}}).get("max", 30.0)),
            )
    ''')


# ---------------------------------------------------------------------------
# risk_engine.py template
# ---------------------------------------------------------------------------

def _render_risk_engine_py(
    crop: str,
    class_name: str,
    display_name: str,
    disease_risks: list[dict],
) -> str:
    # Split evaluable vs non-evaluable diseases
    evaluable: list[dict] = []
    skipped:   list[dict] = []
    for d in disease_risks:
        if d.get("evaluable_with_current_feeds", True) and d.get("when"):
            evaluable.append(d)
        else:
            skipped.append(d)

    # Generate individual detection functions (zero-indented, module-level)
    detect_funcs: list[str] = []
    detect_names: list[str] = []
    for d in evaluable:
        src = _render_disease_func(d["name"], d["when"])
        if src:
            detect_funcs.append(src)
            detect_names.append(_to_func_slug(d["name"]))

    # ── Disease section block (zero-indented) ────────────────────────────────
    disease_lines: list[str] = [
        "# ── Disease detection (auto-generated from BAMIS disease risk conditions) ────",
    ]
    for fn in detect_funcs:
        disease_lines.append("")
        disease_lines.append(fn)
    if skipped:
        disease_lines.append("")
        disease_lines.append(
            "# The following diseases need variables absent from current weather feeds"
        )
        disease_lines.append("# and are not evaluated at runtime:")
        for d in skipped:
            needed = ", ".join(d.get("requires_additional_variables", ["unknown"]))
            disease_lines.append(f"#   {d['name']}  (needs: {needed})")
    disease_block = "\n".join(disease_lines)

    # ── get_disease_risks (zero-indented) ────────────────────────────────────
    gr_lines = [
        "def get_disease_risks(day: DailyForecastPoint) -> list[str]:",
        '    """Return active disease risk strings for one forecast day."""',
        "    risks: list[str] = []",
    ]
    for slug in detect_names:
        gr_lines.append(f"    r = detect_{slug}(day)")
        gr_lines.append("    if r: risks.append(r)")
    if not detect_names:
        gr_lines.append("    # No evaluable disease conditions defined for this crop")
    gr_lines.append("    return risks")
    get_risk_block = "\n".join(gr_lines)

    # ── Assemble full module (zero-indented throughout) ───────────────────────
    # We build sections as separate strings and join, avoiding dedent() confusion
    # when interpolated blocks have different base indentation.

    header = (
        f'"""\n'
        f"{display_name} risk evaluator.\n"
        f"Auto-generated by build_crop_profiles_pipeline.py — do not edit manually.\n"
        f"Uses DayForecast dicts as stored in ArangoDB weather_forecasts collection.\n"
        f'"""\n'
        f"from __future__ import annotations\n"
        f"\n"
        f"from dataclasses import dataclass\n"
        f"\n"
        f"from app.crops.{crop}.profile import {class_name}Thresholds\n"
        f"\n"
        f'_TIER_LABELS = {{0: "Normal", 1: "Advisory", 2: "Warning", 3: "Severe", 4: "Emergency"}}\n'
        f"\n"
        f"\n"
        f"@dataclass\n"
        f"class DailyForecastPoint:\n"
        f"    date: str\n"
        f"    temp_min: float\n"
        f"    temp_max: float\n"
        f"    humidity_max: float\n"
        f"    rain_mm: float\n"
        f"    wind_kmh: float\n"
        f"    source: str\n"
        f"\n"
        f"\n"
        f"def to_point_from_dict(day: dict, source: str) -> DailyForecastPoint:\n"
        f'    """Convert a raw ArangoDB DayForecast dict to DailyForecastPoint."""\n'
        f"    return DailyForecastPoint(\n"
        f'        date=day["date"],\n'
        f'        temp_min=day["temperature"]["min"],\n'
        f'        temp_max=day["temperature"]["max"],\n'
        f'        humidity_max=day["humidity"],\n'
        f'        rain_mm=day["precipitation"]["value"],\n'
        f'        wind_kmh=day["wind"]["speed"],\n'
        f"        source=source,\n"
        f"    )\n"
    )

    evaluate_fn = (
        f"\n"
        f"\n"
        f"def evaluate_{crop}_day(day: DailyForecastPoint, t: {class_name}Thresholds) -> list[str]:\n"
        f'    """Return threshold breaches for one forecast day."""\n'
        f"    triggers: list[str] = []\n"
        f"\n"
        f"    if day.temp_max > t.temp_max:\n"
        f"        triggers.append(\n"
        f'            f"Max temperature {{day.temp_max:.1f}}°C exceeds {display_name} limit {{t.temp_max:.0f}}°C"\n'
        f"        )\n"
        f"    if day.temp_min < t.temp_min:\n"
        f"        triggers.append(\n"
        f'            f"Min temperature {{day.temp_min:.1f}}°C below {display_name} limit {{t.temp_min:.0f}}°C"\n'
        f"        )\n"
        f"    if day.humidity_max < t.humidity_min or day.humidity_max > t.humidity_max:\n"
        f"        triggers.append(\n"
        f'            f"Humidity {{day.humidity_max:.0f}}% outside {display_name} range "\n'
        f'            f"{{t.humidity_min:.0f}}–{{t.humidity_max:.0f}}%"\n'
        f"        )\n"
        f"    if day.rain_mm >= t.rain_critical:\n"
        f'        triggers.append(f"Critical rainfall {{day.rain_mm:.1f}} mm/day")\n'
        f"    elif day.rain_mm >= t.rain_medium:\n"
        f'        triggers.append(f"High rainfall {{day.rain_mm:.1f}} mm/day")\n'
        f"    if day.wind_kmh > t.wind_max:\n"
        f"        triggers.append(\n"
        f'            f"Wind {{day.wind_kmh:.0f}} km/h exceeds {display_name} limit {{t.wind_max:.0f}} km/h"\n'
        f"        )\n"
        f"\n"
        f"    return triggers\n"
    )

    classify_fn = (
        "\n"
        "\n"
        "def classify_tier(triggers: list[str], flood_confirmed: bool = False) -> tuple[int, str]:\n"
        '    """Map trigger list to severity tier (0=Normal … 4=Emergency)."""\n'
        "    severe = 0\n"
        "    advisory = 0\n"
        "    for trig in triggers:\n"
        "        t_lower = trig.lower()\n"
        '        if "critical rainfall" in t_lower:\n'
        "            severe += 1\n"
        '        elif "temperature" in t_lower or "wind" in t_lower or "high rainfall" in t_lower:\n'
        "            severe += 1\n"
        "        else:\n"
        "            advisory += 1\n"
        "\n"
        "    if severe == 0 and advisory == 0:\n"
        "        tier = 0\n"
        "    elif severe == 0:\n"
        "        tier = 1\n"
        "    elif severe == 1:\n"
        "        tier = 2\n"
        "    else:\n"
        "        tier = 3\n"
        "\n"
        "    if flood_confirmed and tier >= 3:\n"
        "        tier = min(tier + 1, 4)\n"
        "    return tier, _TIER_LABELS[tier]\n"
    )

    push_fn = (
        f"\n"
        f"\n"
        f"def build_push_message(assessment: dict) -> str:\n"
        f"    location      = assessment[\"location\"]\n"
        f"    forecast_date = assessment.get(\"forecast_date\", \"\")\n"
        f"    tier          = assessment.get(\"tier\", 0)\n"
        f"    triggers      = assessment.get(\"triggers\", [])\n"
        f"    disease_risks = assessment.get(\"disease_risks\", [])\n"
        f"\n"
        f"    if tier >= 4:\n"
        f"        return (\n"
        f'            f"{display_name} emergency for {{location}}: severe weather and flood risk "\n'
        f'            f"expected on {{forecast_date}}. Protect fields now."\n'
        f"        )\n"
        f"    if triggers:\n"
        f"        return (\n"
        f'            f"{display_name} warning for {{location}} on {{forecast_date}}: "\n'
        f'            f"{{triggers[0]}}. Take protective action today."\n'
        f"        )\n"
        f"    if disease_risks:\n"
        f"        return (\n"
        f'            f"{display_name} advisory for {{location}}: "\n'
        f'            f"{{disease_risks[0]}}. Monitor field conditions closely."\n'
        f"        )\n"
        f'    return f"{display_name} weather update for {{location}}: monitor conditions."\n'
    )

    return (
        header
        + evaluate_fn
        + "\n\n"
        + disease_block
        + "\n\n\n"
        + get_risk_block
        + classify_fn
        + push_fn
    )


# ---------------------------------------------------------------------------
# Directory writer
# ---------------------------------------------------------------------------

def generate_all_modules(
    profile_json: Path,
    crops_dir: Path,
    crop_filter: str | None = None,
    overwrite: bool = True,
    verbose: bool = True,
) -> list[Path]:
    """
    Generate app/crops/<crop>/ modules for every crop in profile_json.
    Returns list of written file paths.
    """
    with open(profile_json, encoding="utf-8") as f:
        profiles: dict[str, dict] = json.load(f)

    # Group profile keys by crop
    crop_regions: dict[str, list[str]] = {}
    for key in profiles:
        parts = key.split("_", 1)
        if len(parts) != 2:
            continue
        crop, region = parts[0], parts[1]
        crop_regions.setdefault(crop, []).append(region)

    written: list[Path] = []

    for crop, regions in sorted(crop_regions.items()):
        if crop_filter and crop != crop_filter:
            continue

        class_name   = _to_class_name(crop)
        display_name = _to_display_name(crop)

        # Use the first key found to get disease risks (risks are per-crop, same across regions)
        first_key = next(k for k in profiles if k.startswith(f"{crop}_"))
        disease_risks = profiles[first_key].get("disease_risks", [])

        # Best default region: "dhaka" if present, else first alphabetically
        default_region = "dhaka" if "dhaka" in regions else sorted(regions)[0]

        crop_dir = crops_dir / crop
        crop_dir.mkdir(parents=True, exist_ok=True)

        files_to_write = {
            crop_dir / "__init__.py": "",
            crop_dir / "profile.py": _render_profile_py(
                crop, class_name, display_name, regions, default_region
            ),
            crop_dir / "risk_engine.py": _render_risk_engine_py(
                crop, class_name, display_name, disease_risks
            ),
        }

        for path, content in files_to_write.items():
            if path.exists() and not overwrite:
                if verbose:
                    print(f"  [SKIP] {path.relative_to(crops_dir.parent.parent)} (exists, --no-overwrite)")
                continue
            path.write_text(content, encoding="utf-8")
            written.append(path)

        if verbose:
            evaluable = sum(
                1 for d in disease_risks
                if d.get("evaluable_with_current_feeds", True) and d.get("when")
            )
            print(
                f"  [OK] {crop:30s}  regions={len(regions)}  "
                f"diseases={len(disease_risks)} ({evaluable} evaluable)"
            )

    return written


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    ap = argparse.ArgumentParser(
        description="Generate app/crops/<crop>/ Python modules from example_crop_profile.json"
    )
    ap.add_argument(
        "--profile", type=Path, default=_DEFAULT_PROFILE,
        help=f"Path to example_crop_profile.json (default: {_DEFAULT_PROFILE})",
    )
    ap.add_argument(
        "--crops-dir", type=Path, default=_DEFAULT_CROPS_DIR,
        help=f"Output parent dir for crop modules (default: {_DEFAULT_CROPS_DIR})",
    )
    ap.add_argument("--crop", default=None, help="Generate only this crop")
    ap.add_argument(
        "--no-overwrite", action="store_true",
        help="Skip crops whose module directory already exists",
    )
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    if not args.profile.exists():
        sys.exit(f"[ERROR] Profile not found: {args.profile}\n"
                 "        Run the pipeline first to generate example_crop_profile.json.")

    print(f"[INFO] Generating crop modules → {args.crops_dir}")
    written = generate_all_modules(
        profile_json=args.profile,
        crops_dir=args.crops_dir,
        crop_filter=args.crop,
        overwrite=not args.no_overwrite,
        verbose=not args.quiet,
    )
    print(f"[DONE] Wrote {len(written)} files")


if __name__ == "__main__":
    main()
