syntax = "proto3";

package tempopb;

import "opentelemetry/proto/trace/v1/trace.proto";

enum PartialStatus {
  PARTIAL_STATUS_UNSPECIFIED = 0;
  PARTIAL_STATUS_OK = 1;
  PARTIAL_STATUS_ERROR = 2;
}

message TraceMetrics {
  uint64 traceCountTotal = 1;
  uint64 traceCountExemplar = 2;
  uint64 spansPerTraceCount = 3;
}

message Trace {
  repeated opentelemetry.proto.trace.v1.ResourceSpans resourceSpans = 1;
}

message TraceByIDResponse {
  Trace trace = 1;
  TraceMetrics metrics = 2;
  PartialStatus status = 3;
}
